/home/runner/work/LibC/LibC/include/signal.h File Reference
Defines functions to handle async events in a proc.
#include <libc_common.h>
#include <platform.h>
#include <sys/types.h>
Classes
union sigval
A payload to pass along with a signal.
struct sigevent
Define how to notify the process when an event is fired.
struct _siginfo
Defines the cause and origin of a signal.
struct sigaction
Define what happens when receiving a specific signal.
struct _stack
Provides information about a stack.
struct _ucontext
Defines the information needed to resume to a userspace context.
Macros
#define SIG_DFL 1
Request default signal handling.
#define SIG_ERR 2
Call to signal() resulted in an error.
#define SIG_IGN 3
Ignore the signal.
#define SIGEV_NONE
Dont notify the process.
#define SIGEV_SIGNAL
Queue a signal with a value.
#define SIGEV_THREAD
Spin up a thread and call a function.
#define _NSIG 64
How many signals this LibC supports.
#define SIGRTMIN 32
Lowest possible signal value (0-31 are reserved)
#define SIGRTMAX (_NSIG - 1)
Highest possible signal value.
#define SIG2STR_MAX 32
The size of the buffer required to hold a string returned by sig2str()
#define SIGHUP 1
Hangup.
#define SIGINT 2
Terminal interrupt.
#define SIGQUIT 3
Terminal quit.
#define SIGILL 4
Illegal instruction.
#define SIGTRAP 5
Trace/breakpoint trap.
#define SIGABRT 6
Abort.
#define SIGBUS 7
Bus error.
#define SIGFPE 8
Erroneous arithmetic operation.
#define SIGKILL 9
Kill (cannot be caught or ignored)
#define SIGUSR1 10
User-defined signal 1.
#define SIGSEGV 11
Invalid memory reference.
#define SIGUSR2 12
User-defined signal 2.
#define SIGPIPE 13
Write on pipe with no reader.
#define SIGALRM 14
Alarm clock.
#define SIGTERM 15
Termination signal.
#define SIGCHLD 17
Child stopped or terminated.
#define SIGCONT 18
Continue if stopped.
#define SIGSTOP 19
Stop executing (cannot be caught or ignored)
#define SIGTSTP 20
Terminal stop.
#define SIGTTIN 21
Background read from terminal.
#define SIGTTOU 22
Background write to terminal.
#define SIGURG 23
Urgent condition on socket.
#define SIGXCPU 24
CPU time limit exceeded.
#define SIGXFSZ 25
File size limit exceeded.
#define SIGVTALRM 26
Virtual timer expired.
#define SIGPROF 27
Profiling timer expired.
#define SIGWINCH 28
Window size change.
#define SIGSYS 31
Bad system call.
#define SIG_BLOCK 1
Add the signals to the block mask.
#define SIG_UNBLOCK 2
Remove the signals from the block mask.
#define SIG_SETMASK 3
Replace the entire mask.
#define SA_NOCLDSTOP (1 << 0)
Do not generate SIGCHLD when children stop/continue.
#define SA_ONSTACK (1 << 1)
Causes signal delivery to occur on an alternate stack.
#define SA_RESETHAND (1 << 2)
Resets the signal’s handling behavior to the default action before the signal handler begins execution.
#define SA_RESTART (1 << 3)
Automatically restart interrupted system calls.
#define SA_SIGINFO (1 << 4)
Deliver extended signal information to the handler.
#define SA_NOCLDWAIT (1 << 5)
Prevent creation of child processes that have exited but are still waiting for their exit code to be read.
#define SA_NODEFER (1 << 6)
Do not block the signal while its handler runs.
#define SS_ONSTACK (1 << 0)
Handler is executing on the alternate signal stack.
#define SS_DISABLE (1 << 1)
Disable the alternate signal stack.
#define MINSIGSTKSZ 2048
Minimum required size for a signal handler stack.
#define SIGSTKSZ 8192
Default size for the alternate signal stack.
#define ILL_ILLOPC 1
Illegal opcode.
#define ILL_ILLOPN 2
Illegal operand.
#define ILL_ILLADR 3
Illegal addressing mode.
#define ILL_ILLTRP 4
Illegal trap.
#define ILL_PRVOPC 5
Privileged opcode.
#define ILL_PRVREG 6
Privileged register.
#define ILL_COPROC 7
Coprocessor error.
#define ILL_BADSTK 8
Internal stack error.
#define FPE_INTDIV 1
Integer div by zero.
#define FPE_INTOVF 2
Integer overflow.
#define FPE_FLTDIV 3
Float div by zero.
#define FPE_FLTOVF 4
Float overflow.
#define FPE_FLTUND 5
Float underflow.
#define FPE_FLTRES 6
Float inexact result.
#define FPE_FLTINV 7
Invalid float operation.
#define FPE_FLTSUB 8
Subscript out of range.
#define SEGV_MAPERR 1
Address not mapped.
#define SEGV_ACCERR 2
Invalid access permissions.
#define BUS_ADRALN 1
Invalid address alignment.
#define BUS_ADRERR 2
Nonexistent physical address.
#define BUS_OBJERR 3
Object-specific hardware error.
#define TRAP_BRKPT 1
Process breakpoint.
#define TRAP_TRACE 2
Process trace trap.
#define CLD_EXITED 1
Child exited normally.
#define CLD_KILLED 2
Child killed.
#define CLD_DUMPED 3
Child terminated and dumped core.
#define CLD_TRAPPED 4
Traced child trapped.
#define CLD_STOPPED 5
Child stopped.
#define CLD_CONTINUED 6
Stopped child continued.
#define SI_USER 1
Sent by kill()
#define SI_QUEUE 2
Sent by sigqueue()
#define SI_TIMER 3
Timer expiration.
#define SI_ASYNCIO 4
Async I/O completion.
#define SI_MESGQ 5
Message queue arrival.
Typedefs
typedef int sig_atomic_t
typedef unsigned long sigset_t
typedef void(* sighandler_t) (int)
typedef void(* sigev_notify_function_t) (union sigval)
typedef struct _siginfo siginfo_t
typedef void(* sigaction_handler_t) (int, siginfo_t *, void *)
typedef struct _platform_mcontext mcontext_t
Platform specific representation of the CPU context state (registers)
typedef struct _stack stack_t
Public alais of _stack.
typedef struct _ucontext ucontext_t
Public alais of _siginfo.
Functions
int kill (pid_t, int)
Send a sig to a process.
int killpg (pid_t, int)
Send a sig to a process group.
int pthread_kill (pthread_t, int)
Send a sig to a thread.
int raise (int)
Send a sig to the executing process.
int sigqueue (pid_t, int, union sigval)
sighandler_t signal (int signum, sighandler_t handler)
int sigaction (int, const struct sigaction *restrict, struct sigaction *restrict)
int sigprocmask (int, const sigset_t *restrict, sigset_t *restrict)
int pthread_sigmask (int, const sigset_t *restrict, sigset_t *restrict)
int sigemptyset (sigset_t *)
int sigfillset (sigset_t *)
int sigaddset (sigset_t *, int)
int sigdelset (sigset_t *, int)
int sigismember (const sigset_t *, int)
int sigpending (sigset_t *)
int sigsuspend (const sigset_t *)
int sigwait (const sigset_t *restrict, int *restrict)
int sigwaitinfo (const sigset_t *restrict, siginfo_t *restrict)
int sigtimedwait (const sigset_t *restrict, siginfo_t *restrict, const struct timespec *restrict)
int sigaltstack (const stack_t *restrict, stack_t *restrict)
void psignal (int, const char *)
void psiginfo (const siginfo_t *, const char *)
int sig2str (int, char *)
int str2sig (const char *restrict, int *restrict)
Detailed Description
Defines functions to handle async events in a proc.
See also
 https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/signal.h.html
Date
16 December 2025
Author
Max Tyson
Definition in file signal.h.
Macro Definition Documentation
_NSIG
#define _NSIG 64
How many signals this LibC supports.
Definition at line 65 of file signal.h.
BUS_ADRALN
#define BUS_ADRALN 1
Invalid address alignment.
Definition at line 217 of file signal.h.
BUS_ADRERR
#define BUS_ADRERR 2
Nonexistent physical address.
Definition at line 218 of file signal.h.
BUS_OBJERR
#define BUS_OBJERR 3
Object-specific hardware error.
Definition at line 219 of file signal.h.
CLD_CONTINUED
#define CLD_CONTINUED 6
Stopped child continued.
Definition at line 231 of file signal.h.
CLD_DUMPED
#define CLD_DUMPED 3
Child terminated and dumped core.
Definition at line 228 of file signal.h.
CLD_EXITED
#define CLD_EXITED 1
Child exited normally.
Definition at line 226 of file signal.h.
CLD_KILLED
#define CLD_KILLED 2
Child killed.
Definition at line 227 of file signal.h.
CLD_STOPPED
#define CLD_STOPPED 5
Child stopped.
Definition at line 230 of file signal.h.
CLD_TRAPPED
#define CLD_TRAPPED 4
Traced child trapped.
Definition at line 229 of file signal.h.
FPE_FLTDIV
#define FPE_FLTDIV 3
Float div by zero.
Definition at line 205 of file signal.h.
FPE_FLTINV
#define FPE_FLTINV 7
Invalid float operation.
Definition at line 209 of file signal.h.
FPE_FLTOVF
#define FPE_FLTOVF 4
Float overflow.
Definition at line 206 of file signal.h.
FPE_FLTRES
#define FPE_FLTRES 6
Float inexact result.
Definition at line 208 of file signal.h.
FPE_FLTSUB
#define FPE_FLTSUB 8
Subscript out of range.
Definition at line 210 of file signal.h.
FPE_FLTUND
#define FPE_FLTUND 5
Float underflow.
Definition at line 207 of file signal.h.
FPE_INTDIV
#define FPE_INTDIV 1
Integer div by zero.
Definition at line 203 of file signal.h.
FPE_INTOVF
#define FPE_INTOVF 2
Integer overflow.
Definition at line 204 of file signal.h.
ILL_BADSTK
#define ILL_BADSTK 8
Internal stack error.
Definition at line 200 of file signal.h.
ILL_COPROC
#define ILL_COPROC 7
Coprocessor error.
Definition at line 199 of file signal.h.
ILL_ILLADR
#define ILL_ILLADR 3
Illegal addressing mode.
Definition at line 195 of file signal.h.
ILL_ILLOPC
#define ILL_ILLOPC 1
Illegal opcode.
Definition at line 193 of file signal.h.
ILL_ILLOPN
#define ILL_ILLOPN 2
Illegal operand.
Definition at line 194 of file signal.h.
ILL_ILLTRP
#define ILL_ILLTRP 4
Illegal trap.
Definition at line 196 of file signal.h.
ILL_PRVOPC
#define ILL_PRVOPC 5
Privileged opcode.
Definition at line 197 of file signal.h.
ILL_PRVREG
#define ILL_PRVREG 6
Privileged register.
Definition at line 198 of file signal.h.
MINSIGSTKSZ
#define MINSIGSTKSZ 2048
Minimum required size for a signal handler stack.
Definition at line 155 of file signal.h.
SA_NOCLDSTOP
#define SA_NOCLDSTOP (1 << 0)
Do not generate SIGCHLD when children stop/continue.
Definition at line 144 of file signal.h.
SA_NOCLDWAIT
#define SA_NOCLDWAIT (1 << 5)
Prevent creation of child processes that have exited but are still waiting for their exit code to be read.
Definition at line 149 of file signal.h.
SA_NODEFER
#define SA_NODEFER (1 << 6)
Do not block the signal while its handler runs.
Definition at line 150 of file signal.h.
SA_ONSTACK
#define SA_ONSTACK (1 << 1)
Causes signal delivery to occur on an alternate stack.
Definition at line 145 of file signal.h.
SA_RESETHAND
#define SA_RESETHAND (1 << 2)
Resets the signal’s handling behavior to the default action before the signal handler begins execution.
Definition at line 146 of file signal.h.
SA_RESTART
#define SA_RESTART (1 << 3)
Automatically restart interrupted system calls.
Definition at line 147 of file signal.h.
SA_SIGINFO
#define SA_SIGINFO (1 << 4)
Deliver extended signal information to the handler.
Definition at line 148 of file signal.h.
SEGV_ACCERR
#define SEGV_ACCERR 2
Invalid access permissions.
Definition at line 214 of file signal.h.
SEGV_MAPERR
#define SEGV_MAPERR 1
Address not mapped.
Definition at line 213 of file signal.h.
SI_ASYNCIO
#define SI_ASYNCIO 4
Async I/O completion.
Definition at line 237 of file signal.h.
SI_MESGQ
#define SI_MESGQ 5
Message queue arrival.
Definition at line 238 of file signal.h.
SI_QUEUE
#define SI_QUEUE 2
Sent by sigqueue()
Definition at line 235 of file signal.h.
SI_TIMER
#define SI_TIMER 3
Timer expiration.
Definition at line 236 of file signal.h.
SI_USER
#define SI_USER 1
Sent by kill()
Definition at line 234 of file signal.h.
SIG2STR_MAX
#define SIG2STR_MAX 32
The size of the buffer required to hold a string returned by sig2str()
Definition at line 68 of file signal.h.
SIG_BLOCK
#define SIG_BLOCK 1
Add the signals to the block mask.
Definition at line 140 of file signal.h.
SIG_DFL
#define SIG_DFL 1
Request default signal handling.
Definition at line 21 of file signal.h.
SIG_ERR
#define SIG_ERR 2
Call to signal() resulted in an error.
Definition at line 22 of file signal.h.
SIG_IGN
#define SIG_IGN 3
Ignore the signal.
Definition at line 23 of file signal.h.
SIG_SETMASK
#define SIG_SETMASK 3
Replace the entire mask.
Definition at line 142 of file signal.h.
SIG_UNBLOCK
#define SIG_UNBLOCK 2
Remove the signals from the block mask.
Definition at line 141 of file signal.h.
SIGABRT
#define SIGABRT 6
Abort.
Definition at line 75 of file signal.h.
SIGALRM
#define SIGALRM 14
Alarm clock.
Definition at line 83 of file signal.h.
SIGBUS
#define SIGBUS 7
Bus error.
Definition at line 76 of file signal.h.
SIGCHLD
#define SIGCHLD 17
Child stopped or terminated.
Definition at line 86 of file signal.h.
SIGCONT
#define SIGCONT 18
Continue if stopped.
Definition at line 87 of file signal.h.
SIGEV_NONE
#define SIGEV_NONE
Dont notify the process.
Definition at line 61 of file signal.h.
SIGEV_SIGNAL
#define SIGEV_SIGNAL
Queue a signal with a value.
Definition at line 62 of file signal.h.
SIGEV_THREAD
#define SIGEV_THREAD
Spin up a thread and call a function.
Definition at line 63 of file signal.h.
SIGFPE
#define SIGFPE 8
Erroneous arithmetic operation.
Definition at line 77 of file signal.h.
SIGHUP
#define SIGHUP 1
Hangup.
Definition at line 70 of file signal.h.
SIGILL
#define SIGILL 4
Illegal instruction.
Definition at line 73 of file signal.h.
SIGINT
#define SIGINT 2
Terminal interrupt.
Definition at line 71 of file signal.h.
SIGKILL
#define SIGKILL 9
Kill (cannot be caught or ignored)
Definition at line 78 of file signal.h.
SIGPIPE
#define SIGPIPE 13
Write on pipe with no reader.
Definition at line 82 of file signal.h.
SIGPROF
#define SIGPROF 27
Profiling timer expired.
Definition at line 97 of file signal.h.
SIGQUIT
#define SIGQUIT 3
Terminal quit.
Definition at line 72 of file signal.h.
SIGRTMAX
#define SIGRTMAX (_NSIG - 1)
Highest possible signal value.
Definition at line 67 of file signal.h.
SIGRTMIN
#define SIGRTMIN 32
Lowest possible signal value (0-31 are reserved)
Definition at line 66 of file signal.h.
SIGSEGV
#define SIGSEGV 11
Invalid memory reference.
Definition at line 80 of file signal.h.
SIGSTKSZ
#define SIGSTKSZ 8192
Default size for the alternate signal stack.
Definition at line 156 of file signal.h.
SIGSTOP
#define SIGSTOP 19
Stop executing (cannot be caught or ignored)
Definition at line 88 of file signal.h.
SIGSYS
#define SIGSYS 31
Bad system call.
Definition at line 99 of file signal.h.
SIGTERM
#define SIGTERM 15
Termination signal.
Definition at line 84 of file signal.h.
SIGTRAP
#define SIGTRAP 5
Trace/breakpoint trap.
Definition at line 74 of file signal.h.
SIGTSTP
#define SIGTSTP 20
Terminal stop.
Definition at line 89 of file signal.h.
SIGTTIN
#define SIGTTIN 21
Background read from terminal.
Definition at line 90 of file signal.h.
SIGTTOU
#define SIGTTOU 22
Background write to terminal.
Definition at line 91 of file signal.h.
SIGURG
#define SIGURG 23
Urgent condition on socket.
Definition at line 93 of file signal.h.
SIGUSR1
#define SIGUSR1 10
User-defined signal 1.
Definition at line 79 of file signal.h.
SIGUSR2
#define SIGUSR2 12
User-defined signal 2.
Definition at line 81 of file signal.h.
SIGVTALRM
#define SIGVTALRM 26
Virtual timer expired.
Definition at line 96 of file signal.h.
SIGWINCH
#define SIGWINCH 28
Window size change.
Definition at line 98 of file signal.h.
SIGXCPU
#define SIGXCPU 24
CPU time limit exceeded.
Definition at line 94 of file signal.h.
SIGXFSZ
#define SIGXFSZ 25
File size limit exceeded.
Definition at line 95 of file signal.h.
SS_DISABLE
#define SS_DISABLE (1 << 1)
Disable the alternate signal stack.
Definition at line 153 of file signal.h.
SS_ONSTACK
#define SS_ONSTACK (1 << 0)
Handler is executing on the alternate signal stack.
Definition at line 152 of file signal.h.
TRAP_BRKPT
#define TRAP_BRKPT 1
Process breakpoint.
Definition at line 222 of file signal.h.
TRAP_TRACE
#define TRAP_TRACE 2
Process trace trap.
Definition at line 223 of file signal.h.
Typedef Documentation
mcontext_t
typedef struct _platform_mcontext mcontext_t
Platform specific representation of the CPU context state (registers)
Definition at line 159 of file signal.h.
sig_atomic_t
typedef int sig_atomic_t
Definition at line 25 of file signal.h.
sigaction_handler_t
typedef void(* sigaction_handler_t) (int, siginfo_t *, void *)
Definition at line 121 of file signal.h.
sigev_notify_function_t
typedef void(* sigev_notify_function_t) (union sigval)
Definition at line 45 of file signal.h.
sighandler_t
typedef void(* sighandler_t) (int)
Definition at line 33 of file signal.h.
sigset_t
typedef unsigned long sigset_t
Definition at line 26 of file signal.h.
ucontext_t
ucontext_t
Public alais of _siginfo.
Public alais of _ucontext.
Function Documentation
kill()
int kill (pid_t pid, int sig)
Send a sig to a process.
Parameters
pid The process (or process group if negative) to send the sig to
sig The sig to send
Returns
0 on success, or -1 with an errno
Definition at line 21 of file signal.c.
{
    // Ensure a valid sig
    if(sig < 0 || sig >= _NSIG)
        RETURN_ERR(EINVAL);
    // Send the kill sig (platform specific)
    return _platform_kill(pid,sig);
}
References _NSIG, _platform_kill(), and EINVAL.
Referenced by killpg(), and raise().
killpg()
int killpg (pid_t pgid, int sig)
Send a sig to a process group.
Parameters
pgid The process group to send the sig to
sig The sig to send
Returns
0 on success, or -1 with an errno
Definition at line 39 of file signal.c.
{
    // IDs must be positive as platform expects negatives to represent a group which fails under -(-pgid)
    if (pgid < 0)
        RETURN_ERR(EINVAL);
    // Send the kill sig and make it a group (platform specific)
    return kill(-pgid,sig);
}
References EINVAL, and kill().
pthread_kill()
int pthread_kill (pthread_t thread, int sig)
Send a sig to a thread.
Parameters
thread The destination thread to send the sig to
sig The sig to send
Returns
0 on success, or -1 with an errno
Definition at line 58 of file signal.c.
                                           {
    // TODO: POSIX pthreads support
    return -1;
}
raise()
int raise (int sig)
Send a sig to the executing process.
Returns
0 on success, or -1 with an errno
Definition at line 70 of file signal.c.
                  {
    // Ensure a valid sig
    if(sig < 0 || sig >= _NSIG)
        RETURN_ERR(EINVAL);
    return kill(_platform_getpid(), sig);
}
References _NSIG, _platform_getpid(), EINVAL, and kill().