/home/runner/work/LibC/LibC/src/signal.c File Reference
Defines functions to handle async events in a proc.
#include <signal.h>
#include <platform.h>
#include <errno.h>
Functions
int kill (pid_t pid, int sig)
Send a sig to a process.
int killpg (pid_t pgid, int sig)
Send a sig to a process group.
int pthread_kill (pthread_t thread, int sig)
Send a sig to a thread.
int raise (int sig)
Send a sig to the executing process.
Detailed Description
Defines functions to handle async events in a proc.
Date
16 December 2025
Author
Max Tyson
Definition in file signal.c.
Function Documentation
kill()
int kill (pid_t pid, int sig)
Send a sig to a process.
Parameters
pid The process (or process group if negative) to send the sig to
sig The sig to send
Returns
0 on success, or -1 with an errno
Definition at line 21 of file signal.c.
{
    // Ensure a valid sig
    if(sig < 0 || sig >= _NSIG)
        RETURN_ERR(EINVAL);
    // Send the kill sig (platform specific)
    return _platform_kill(pid,sig);
}
References _NSIG, _platform_kill(), and EINVAL.
Referenced by killpg(), and raise().
killpg()
int killpg (pid_t pgid, int sig)
Send a sig to a process group.
Parameters
pgid The process group to send the sig to
sig The sig to send
Returns
0 on success, or -1 with an errno
Definition at line 39 of file signal.c.
{
    // IDs must be positive as platform expects negatives to represent a group which fails under -(-pgid)
    if (pgid < 0)
        RETURN_ERR(EINVAL);
    // Send the kill sig and make it a group (platform specific)
    return kill(-pgid,sig);
}
References EINVAL, and kill().
pthread_kill()
int pthread_kill (pthread_t thread, int sig)
Send a sig to a thread.
Parameters
thread The destination thread to send the sig to
sig The sig to send
Returns
0 on success, or -1 with an errno
Definition at line 58 of file signal.c.
                                           {
    // TODO: POSIX pthreads support
    return -1;
}
raise()
int raise (int sig)
Send a sig to the executing process.
Returns
0 on success, or -1 with an errno
Definition at line 70 of file signal.c.
                  {
    // Ensure a valid sig
    if(sig < 0 || sig >= _NSIG)
        RETURN_ERR(EINVAL);
    return kill(_platform_getpid(), sig);
}
References _NSIG, _platform_getpid(), EINVAL, and kill().