.TH "__locale" 3 "Version 0.3" "LibC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__locale \- Private struct containing local data for each category\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <locale\&.h>\fP
.SH "Detailed Description"
.PP 
Private struct containing local data for each category\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for LibC from the source code\&.
