.TH "_ldiv" 3 "Version 0.3" "LibC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_ldiv \- Internal representation for the result of a ldiv() call\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stdlib\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "long \fBquot\fP"
.br
.RI "Quotient\&. "
.ti -1c
.RI "long \fBrem\fP"
.br
.RI "Remainder\&. "
.in -1c
.SH "Detailed Description"
.PP 
Internal representation for the result of a ldiv() call\&. 
.PP
Definition at line \fB49\fP of file \fBstdlib\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "long _ldiv::quot"

.PP
Quotient\&. 
.PP
Definition at line \fB51\fP of file \fBstdlib\&.h\fP\&.
.SS "long _ldiv::rem"

.PP
Remainder\&. 
.PP
Definition at line \fB52\fP of file \fBstdlib\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LibC from the source code\&.
