.TH "_platform_mcontext" 3 "Version 0.3" "LibC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_platform_mcontext
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Definition at line \fB49\fP of file \fBexample\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LibC from the source code\&.
