.TH "_siginfo" 3 "Version 0.3" "LibC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_siginfo \- Defines the cause and origin of a signal\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <signal\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBsi_signo\fP"
.br
.RI "Signal number\&. "
.ti -1c
.RI "int \fBsi_code\fP"
.br
.RI "Signal code\&. "
.ti -1c
.RI "int \fBsi_errno\fP"
.br
.RI "If non-zero, an errno value associated with this signal, as described in <\fBerrno\&.h\fP>\&. "
.ti -1c
.RI "\fBpid_t\fP \fBsi_pid\fP"
.br
.RI "Sending process ID\&. "
.ti -1c
.RI "\fBuid_t\fP \fBsi_uid\fP"
.br
.RI "User ID of sending process\&. "
.ti -1c
.RI "void * \fBsi_addr\fP"
.br
.RI "Address that caused fault\&. "
.ti -1c
.RI "int \fBsi_status\fP"
.br
.RI "Exit value or signal\&. "
.ti -1c
.RI "union \fBsigval\fP \fBsi_value\fP"
.br
.RI "Signal value\&. "
.in -1c
.SH "Detailed Description"
.PP 
Defines the cause and origin of a signal\&. 
.PP
Definition at line \fB109\fP of file \fBsignal\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "void* _siginfo::si_addr"

.PP
Address that caused fault\&. 
.PP
Definition at line \fB116\fP of file \fBsignal\&.h\fP\&.
.SS "int _siginfo::si_code"

.PP
Signal code\&. 
.PP
Definition at line \fB112\fP of file \fBsignal\&.h\fP\&.
.SS "int _siginfo::si_errno"

.PP
If non-zero, an errno value associated with this signal, as described in <\fBerrno\&.h\fP>\&. 
.PP
Definition at line \fB113\fP of file \fBsignal\&.h\fP\&.
.SS "\fBpid_t\fP _siginfo::si_pid"

.PP
Sending process ID\&. 
.PP
Definition at line \fB114\fP of file \fBsignal\&.h\fP\&.
.SS "int _siginfo::si_signo"

.PP
Signal number\&. 
.PP
Definition at line \fB111\fP of file \fBsignal\&.h\fP\&.
.SS "int _siginfo::si_status"

.PP
Exit value or signal\&. 
.PP
Definition at line \fB117\fP of file \fBsignal\&.h\fP\&.
.SS "\fBuid_t\fP _siginfo::si_uid"

.PP
User ID of sending process\&. 
.PP
Definition at line \fB115\fP of file \fBsignal\&.h\fP\&.
.SS "union \fBsigval\fP _siginfo::si_value"

.PP
Signal value\&. 
.PP
Definition at line \fB118\fP of file \fBsignal\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LibC from the source code\&.
