.TH "_stack" 3 "Version 0.3" "LibC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_stack \- Provides information about a stack\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <signal\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void * \fBss_sp\fP"
.br
.RI "Stack base or pointer\&. "
.ti -1c
.RI "size_t \fBss_size\fP"
.br
.RI "Stack size in bytes\&. "
.ti -1c
.RI "int \fBss_flags\fP"
.br
.RI "Flags\&. "
.in -1c
.SH "Detailed Description"
.PP 
Provides information about a stack\&. 
.PP
Definition at line \fB168\fP of file \fBsignal\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int _stack::ss_flags"

.PP
Flags\&. 
.PP
Definition at line \fB172\fP of file \fBsignal\&.h\fP\&.
.SS "size_t _stack::ss_size"

.PP
Stack size in bytes\&. 
.PP
Definition at line \fB171\fP of file \fBsignal\&.h\fP\&.
.SS "void* _stack::ss_sp"

.PP
Stack base or pointer\&. 
.PP
Definition at line \fB170\fP of file \fBsignal\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LibC from the source code\&.
