.TH "_struct_platform_locale" 3 "Version 0.3" "LibC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_struct_platform_locale \- Platform specific implementation for storing locale information\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <example\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBcollate\fP"
.br
.ti -1c
.RI "const char * \fBctype\fP"
.br
.ti -1c
.RI "const char * \fBmessages\fP"
.br
.ti -1c
.RI "const char * \fBmonetary\fP"
.br
.ti -1c
.RI "const char * \fBnumeric\fP"
.br
.ti -1c
.RI "const char * \fBtime\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Platform specific implementation for storing locale information\&. 
.PP
Definition at line \fB60\fP of file \fBexample\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "const char* _struct_platform_locale::collate"

.PP
Definition at line \fB62\fP of file \fBexample\&.h\fP\&.
.SS "const char* _struct_platform_locale::ctype"

.PP
Definition at line \fB63\fP of file \fBexample\&.h\fP\&.
.SS "const char* _struct_platform_locale::messages"

.PP
Definition at line \fB64\fP of file \fBexample\&.h\fP\&.
.SS "const char* _struct_platform_locale::monetary"

.PP
Definition at line \fB65\fP of file \fBexample\&.h\fP\&.
.SS "const char* _struct_platform_locale::numeric"

.PP
Definition at line \fB66\fP of file \fBexample\&.h\fP\&.
.SS "const char* _struct_platform_locale::time"

.PP
Definition at line \fB67\fP of file \fBexample\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LibC from the source code\&.
