.TH "_ucontext" 3 "Version 0.3" "LibC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_ucontext \- Defines the information needed to resume to a userspace context\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <signal\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fB_ucontext\fP * \fBuc_link\fP"
.br
.RI "Pointer to the context that is resumed when this context returns\&. "
.ti -1c
.RI "sigset_t \fBuc_sigmask\fP"
.br
.RI "The set of signals that are blocked when this context is active\&. "
.ti -1c
.RI "\fBstack_t\fP \fBuc_stack\fP"
.br
.RI "The stack used by this context\&. "
.ti -1c
.RI "\fBmcontext_t\fP \fBuc_mcontext\fP"
.br
.RI "A machine-specific representation of the saved context\&. "
.in -1c
.SH "Detailed Description"
.PP 
Defines the information needed to resume to a userspace context\&. 
.PP
Definition at line \fB183\fP of file \fBsignal\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "struct \fB_ucontext\fP* _ucontext::uc_link"

.PP
Pointer to the context that is resumed when this context returns\&. 
.PP
Definition at line \fB185\fP of file \fBsignal\&.h\fP\&.
.SS "\fBmcontext_t\fP _ucontext::uc_mcontext"

.PP
A machine-specific representation of the saved context\&. 
.PP
Definition at line \fB188\fP of file \fBsignal\&.h\fP\&.
.SS "sigset_t _ucontext::uc_sigmask"

.PP
The set of signals that are blocked when this context is active\&. 
.PP
Definition at line \fB186\fP of file \fBsignal\&.h\fP\&.
.SS "\fBstack_t\fP _ucontext::uc_stack"

.PP
The stack used by this context\&. 
.PP
Definition at line \fB187\fP of file \fBsignal\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LibC from the source code\&.
