.TH "/home/runner/work/LibC/LibC/src/aio.c" 3 "Version 0.3" "LibC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/LibC/LibC/src/aio.c \- Implements functions to handle asynchronous input and output\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <aio\&.h>\fP
.br

.SH "Detailed Description"
.PP 
Implements functions to handle asynchronous input and output\&. 


.PP
\fBDate\fP
.RS 4
28 December 2025 
.RE
.PP
\fBAuthor\fP
.RS 4
Max Tyson 
.RE
.PP

.PP
Definition in file \fBaio\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LibC from the source code\&.
