.TH "aiocb" 3 "Version 0.3" "LibC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aiocb \- Defines an async I/O control block, the parameters that control an I/O operation\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <aio\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBaio_fildes\fP"
.br
.RI "The descriptor of the file to write to\&. "
.ti -1c
.RI "\fBoff_t\fP \fBaio_offset\fP"
.br
.RI "Where in the file to write to\&. "
.ti -1c
.RI "volatile void * \fBaio_buf\fP"
.br
.RI "The data buffer to write from\&. "
.ti -1c
.RI "size_t \fBaio_nbytes\fP"
.br
.RI "Length in bytes of the buffer\&. "
.ti -1c
.RI "int \fBaio_reqprio\fP"
.br
.RI "The priority of the operation (subtracted from the threads priority) "
.ti -1c
.RI "struct \fBsigevent\fP \fBaio_sigevent\fP"
.br
.RI "Signal to notify the thread when the operation completes (\&. "
.ti -1c
.RI "int \fBaio_lio_opcode\fP"
.br
.RI "The type of operation to preform (used only by lio_listio) "
.in -1c
.SH "Detailed Description"
.PP 
Defines an async I/O control block, the parameters that control an I/O operation\&. 
.PP
Definition at line \fB22\fP of file \fBaio\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "volatile void* aiocb::aio_buf"

.PP
The data buffer to write from\&. 
.PP
Definition at line \fB26\fP of file \fBaio\&.h\fP\&.
.SS "int aiocb::aio_fildes"

.PP
The descriptor of the file to write to\&. 
.PP
Definition at line \fB24\fP of file \fBaio\&.h\fP\&.
.SS "int aiocb::aio_lio_opcode"

.PP
The type of operation to preform (used only by lio_listio) 
.PP
Definition at line \fB30\fP of file \fBaio\&.h\fP\&.
.SS "size_t aiocb::aio_nbytes"

.PP
Length in bytes of the buffer\&. 
.PP
Definition at line \fB27\fP of file \fBaio\&.h\fP\&.
.SS "\fBoff_t\fP aiocb::aio_offset"

.PP
Where in the file to write to\&. 
.PP
Definition at line \fB25\fP of file \fBaio\&.h\fP\&.
.SS "int aiocb::aio_reqprio"

.PP
The priority of the operation (subtracted from the threads priority) 
.PP
Definition at line \fB28\fP of file \fBaio\&.h\fP\&.
.SS "struct \fBsigevent\fP aiocb::aio_sigevent"

.PP
Signal to notify the thread when the operation completes (\&. 
.PP
\fBSee also\fP
.RS 4
SIGEV_*) 
.RE
.PP

.PP
Definition at line \fB29\fP of file \fBaio\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LibC from the source code\&.
