.TH "/home/runner/work/LibC/LibC/src/crt0.c" 3 "Version 0.3" "LibC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/LibC/LibC/src/crt0.c \- Defines the _start symbol, where all C,C++ programs enter, sets up the process and runs it\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int, char **, char **)"
.br
.RI "Defined by the program, must exist to link\&. "
.ti -1c
.RI "int \fB_start\fP (int argc, char *argv[], char *env[])"
.br
.in -1c
.SH "Detailed Description"
.PP 
Defines the _start symbol, where all C,C++ programs enter, sets up the process and runs it\&. 


.PP
\fBDate\fP
.RS 4
14th December 2025 
.RE
.PP
\fBAuthor\fP
.RS 4
Max Tyson 
.RE
.PP

.PP
Definition in file \fBcrt0\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "int _start (int argc, char * argv[], char * env[])"

.PP
Definition at line \fB14\fP of file \fBcrt0\&.c\fP\&..PP
.nf
14                                                 {
15 
16 
17     // Execute the program and exit with the exit code
18     const int ret = main(argc, argv, env);
19     exit(ret);
20 
21     // Failed to exit
22     return \-1;
23 }
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for LibC from the source code\&.
