.TH "/home/runner/work/LibC/LibC/src/errno.c" 3 "Version 0.3" "LibC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/LibC/LibC/src/errno.c \- Implements where the error codes are stored\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <errno\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int * \fB__errno_location\fP (void)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fB__errno\fP = 0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Implements where the error codes are stored\&. 


.PP
\fBDate\fP
.RS 4
14 December 2025 
.RE
.PP
\fBAuthor\fP
.RS 4
Max Tyson 
.RE
.PP

.PP
Definition in file \fBerrno\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "int * __errno_location (void)"

.PP
Definition at line \fB15\fP of file \fBerrno\&.c\fP\&..PP
.nf
15                             {
16  return &__errno_storage;
17 }
.fi

.SH "Variable Documentation"
.PP 
.SS "int __errno = 0"

.PP
Definition at line \fB12\fP of file \fBerrno\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LibC from the source code\&.
