.TH "itimerspec" 3 "Version 0.3" "LibC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
itimerspec \- Defines when an interval timer should fire\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <time\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBtimespec\fP \fBit_interval\fP"
.br
.RI "Reload value (period) "
.ti -1c
.RI "struct \fBtimespec\fP \fBit_value\fP"
.br
.RI "Initial expiration\&. "
.in -1c
.SH "Detailed Description"
.PP 
Defines when an interval timer should fire\&. 
.PP
Definition at line \fB54\fP of file \fBtime\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "struct \fBtimespec\fP itimerspec::it_interval"

.PP
Reload value (period) 
.PP
Definition at line \fB56\fP of file \fBtime\&.h\fP\&.
.SS "struct \fBtimespec\fP itimerspec::it_value"

.PP
Initial expiration\&. 
.PP
Definition at line \fB57\fP of file \fBtime\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LibC from the source code\&.
