.TH "lconv" 3 "Version 0.3" "LibC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lconv \- Defines local specfic formating for numbers and money\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <locale\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBdecimal_point\fP"
.br
.RI "String used to separate the whole part of the number from the fraction part\&. "
.ti -1c
.RI "char * \fBthousands_sep\fP"
.br
.RI "String used to separate digit groups\&. "
.ti -1c
.RI "char * \fBgrouping\fP"
.br
.RI "How to group digits\&. "
.ti -1c
.RI "char * \fBcurrency_symbol\fP"
.br
.RI "Local currency symbol (ie '$') "
.ti -1c
.RI "char * \fBint_curr_symbol\fP"
.br
.RI "4 character international currency symbol (ISO 4217) "
.ti -1c
.RI "char * \fBmon_decimal_point\fP"
.br
.RI "String used to separate the whole part of the monetary value from the fraction part\&. "
.ti -1c
.RI "char * \fBmon_thousands_sep\fP"
.br
.RI "String used to separate monetary digit groups\&. "
.ti -1c
.RI "char * \fBmon_grouping\fP"
.br
.RI "How to group monetary digits\&. "
.ti -1c
.RI "char \fBfrac_digits\fP"
.br
.RI "How many digits does the local currency use for decimals\&. "
.ti -1c
.RI "char \fBint_frac_digits\fP"
.br
.RI "How many digits does the internation currency use for decimals\&. "
.ti -1c
.RI "char * \fBpositive_sign\fP"
.br
.RI "String used to denote a positive value\&. "
.ti -1c
.RI "char * \fBnegative_sign\fP"
.br
.RI "String used to denote a negative value\&. "
.ti -1c
.RI "char \fBp_cs_precedes\fP"
.br
.RI "Where to place the currency symbol for a positive value (after = 0, before = 1) "
.ti -1c
.RI "char \fBn_cs_precedes\fP"
.br
.RI "Where to place the currency symbol for a negative value (after = 0, before = 1) "
.ti -1c
.RI "char \fBp_sep_by_space\fP"
.br
.RI "Whether to add a space between a positive value and the symbol (boolean) "
.ti -1c
.RI "char \fBn_sep_by_space\fP"
.br
.RI "Whether to add a space between a negative value and the symbol (boolean) "
.ti -1c
.RI "char \fBint_p_cs_precedes\fP"
.br
.RI "Where to place the currency symbol for a positive international value (after = 0, before = 1) "
.ti -1c
.RI "char \fBint_n_cs_precedes\fP"
.br
.RI "Where to place the currency symbol for a negative international value (after = 0, before = 1) "
.ti -1c
.RI "char \fBint_p_sep_by_space\fP"
.br
.RI "Whether to add a space between a positive international value and the symbol (boolean) "
.ti -1c
.RI "char \fBint_n_sep_by_space\fP"
.br
.RI "Whether to add a space between a negative international value and the symbol (boolean) "
.ti -1c
.RI "char \fBp_sign_posn\fP"
.br
.RI "Where to place the positive sign (\&. "
.ti -1c
.RI "char \fBn_sign_posn\fP"
.br
.RI "Where to place the negative sign (\&. "
.ti -1c
.RI "char \fBint_p_sign_posn\fP"
.br
.RI "Where to place the positive sign for an international value (\&. "
.ti -1c
.RI "char \fBint_n_sign_posn\fP"
.br
.RI "Where to place the negative sign for an international value (\&. "
.in -1c
.SH "Detailed Description"
.PP 
Defines local specfic formating for numbers and money\&. 
.PP
Definition at line \fB38\fP of file \fBlocale\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "char* lconv::currency_symbol"

.PP
Local currency symbol (ie '$') 
.PP
Definition at line \fB44\fP of file \fBlocale\&.h\fP\&.
.SS "char* lconv::decimal_point"

.PP
String used to separate the whole part of the number from the fraction part\&. 
.PP
Definition at line \fB40\fP of file \fBlocale\&.h\fP\&.
.SS "char lconv::frac_digits"

.PP
How many digits does the local currency use for decimals\&. 
.PP
Definition at line \fB51\fP of file \fBlocale\&.h\fP\&.
.SS "char* lconv::grouping"

.PP
How to group digits\&. 
.PP
Definition at line \fB42\fP of file \fBlocale\&.h\fP\&.
.SS "char* lconv::int_curr_symbol"

.PP
4 character international currency symbol (ISO 4217) 
.PP
Definition at line \fB45\fP of file \fBlocale\&.h\fP\&.
.SS "char lconv::int_frac_digits"

.PP
How many digits does the internation currency use for decimals\&. 
.PP
Definition at line \fB52\fP of file \fBlocale\&.h\fP\&.
.SS "char lconv::int_n_cs_precedes"

.PP
Where to place the currency symbol for a negative international value (after = 0, before = 1) 
.PP
Definition at line \fB63\fP of file \fBlocale\&.h\fP\&.
.SS "char lconv::int_n_sep_by_space"

.PP
Whether to add a space between a negative international value and the symbol (boolean) 
.PP
Definition at line \fB65\fP of file \fBlocale\&.h\fP\&.
.SS "char lconv::int_n_sign_posn"

.PP
Where to place the negative sign for an international value (\&. 
.PP
\fBSee also\fP
.RS 4
\fBSignPosition\fP) 
.RE
.PP

.PP
Definition at line \fB71\fP of file \fBlocale\&.h\fP\&.
.SS "char lconv::int_p_cs_precedes"

.PP
Where to place the currency symbol for a positive international value (after = 0, before = 1) 
.PP
Definition at line \fB62\fP of file \fBlocale\&.h\fP\&.
.SS "char lconv::int_p_sep_by_space"

.PP
Whether to add a space between a positive international value and the symbol (boolean) 
.PP
Definition at line \fB64\fP of file \fBlocale\&.h\fP\&.
.SS "char lconv::int_p_sign_posn"

.PP
Where to place the positive sign for an international value (\&. 
.PP
\fBSee also\fP
.RS 4
\fBSignPosition\fP) 
.RE
.PP

.PP
Definition at line \fB70\fP of file \fBlocale\&.h\fP\&.
.SS "char* lconv::mon_decimal_point"

.PP
String used to separate the whole part of the monetary value from the fraction part\&. 
.PP
Definition at line \fB47\fP of file \fBlocale\&.h\fP\&.
.SS "char* lconv::mon_grouping"

.PP
How to group monetary digits\&. 
.PP
Definition at line \fB49\fP of file \fBlocale\&.h\fP\&.
.SS "char* lconv::mon_thousands_sep"

.PP
String used to separate monetary digit groups\&. 
.PP
Definition at line \fB48\fP of file \fBlocale\&.h\fP\&.
.SS "char lconv::n_cs_precedes"

.PP
Where to place the currency symbol for a negative value (after = 0, before = 1) 
.PP
Definition at line \fB58\fP of file \fBlocale\&.h\fP\&.
.SS "char lconv::n_sep_by_space"

.PP
Whether to add a space between a negative value and the symbol (boolean) 
.PP
Definition at line \fB60\fP of file \fBlocale\&.h\fP\&.
.SS "char lconv::n_sign_posn"

.PP
Where to place the negative sign (\&. 
.PP
\fBSee also\fP
.RS 4
\fBSignPosition\fP) 
.RE
.PP

.PP
Definition at line \fB68\fP of file \fBlocale\&.h\fP\&.
.SS "char* lconv::negative_sign"

.PP
String used to denote a negative value\&. 
.PP
Definition at line \fB55\fP of file \fBlocale\&.h\fP\&.
.SS "char lconv::p_cs_precedes"

.PP
Where to place the currency symbol for a positive value (after = 0, before = 1) 
.PP
Definition at line \fB57\fP of file \fBlocale\&.h\fP\&.
.SS "char lconv::p_sep_by_space"

.PP
Whether to add a space between a positive value and the symbol (boolean) 
.PP
Definition at line \fB59\fP of file \fBlocale\&.h\fP\&.
.SS "char lconv::p_sign_posn"

.PP
Where to place the positive sign (\&. 
.PP
\fBSee also\fP
.RS 4
\fBSignPosition\fP) 
.RE
.PP

.PP
Definition at line \fB67\fP of file \fBlocale\&.h\fP\&.
.SS "char* lconv::positive_sign"

.PP
String used to denote a positive value\&. 
.PP
Definition at line \fB54\fP of file \fBlocale\&.h\fP\&.
.SS "char* lconv::thousands_sep"

.PP
String used to separate digit groups\&. 
.PP
Definition at line \fB41\fP of file \fBlocale\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LibC from the source code\&.
