.TH "/home/runner/work/LibC/LibC/include/libc_platform_specifics.h" 3 "Version 0.3" "LibC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/LibC/LibC/include/libc_platform_specifics.h \- Functions that are specific to the platform that this libc is compiled for\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Functions that are specific to the platform that this libc is compiled for\&. 


.PP
\fBDate\fP
.RS 4
14 December 2025 
.RE
.PP
\fBAuthor\fP
.RS 4
Max Tyson 
.RE
.PP

.PP
Definition in file \fBlibc_platform_specifics\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LibC from the source code\&.
