.TH "/home/runner/work/LibC/LibC/include/libc_common.h" 3 "Version 0.3" "LibC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/LibC/LibC/include/libc_common.h \- Functions and macros that are used often throughout this implmentaion of LibC\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Functions and macros that are used often throughout this implmentaion of LibC\&. 


.PP
\fBDate\fP
.RS 4
14 December 2025 
.RE
.PP
\fBAuthor\fP
.RS 4
Max Tyson 
.RE
.PP

.PP
Definition in file \fBlibc_common\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define CPP_END"

.PP
Definition at line \fB17\fP of file \fBlibc_common\&.h\fP\&.
.SS "#define CPP_START"

.PP
Definition at line \fB16\fP of file \fBlibc_common\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LibC from the source code\&.
