.TH "/home/runner/work/LibC/LibC/src/locale.c" 3 "Version 0.3" "LibC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/LibC/LibC/src/locale.c \- Implements locale management functions\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <locale\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br

.SH "Detailed Description"
.PP 
Implements locale management functions\&. 


.PP
\fBDate\fP
.RS 4
15 December 2025 
.RE
.PP
\fBAuthor\fP
.RS 4
Max Tyson 
.RE
.PP

.PP
Definition in file \fBlocale\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LibC from the source code\&.
