.TH "/home/runner/work/LibC/LibC/include/locale.h" 3 "Version 0.3" "LibC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/LibC/LibC/include/locale.h \- Defines langauge and region specific behaviour\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <libc_common\&.h>\fP
.br
\fC#include <stddef\&.h>\fP
.br
\fC#include <platform\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBlconv\fP"
.br
.RI "Defines local specfic formating for numbers and money\&. "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBLC_ALL\fP   0"
.br
.RI "Set or query all locale categories at once\&. "
.ti -1c
.RI "#define \fBLC_COLLATE\fP   1"
.br
.RI "String collation rules (sorting and comparison order) "
.ti -1c
.RI "#define \fBLC_CTYPE\fP   2"
.br
.RI "Character classification, case conversion, encoding\&. "
.ti -1c
.RI "#define \fBLC_MESSAGES\fP   3"
.br
.RI "Language used for diagnostic and system messages\&. "
.ti -1c
.RI "#define \fBLC_MONETARY\fP   4"
.br
.RI "Currency symbols, monetary formatting, sign placement\&. "
.ti -1c
.RI "#define \fBLC_NUMERIC\fP   5"
.br
.RI "Non-monetary numeric formatting (decimal point, grouping) "
.ti -1c
.RI "#define \fBLC_TIME\fP   6"
.br
.RI "Date and time formatting (month/day names, formats) "
.ti -1c
.RI "#define \fBLC_ALL_MASK\fP   (\fBLC_COLLATE_MASK\fP | \fBLC_CTYPE_MASK\fP | \fBLC_MESSAGES_MASK\fP | \fBLC_MONETARY_MASK\fP | \fBLC_NUMERIC_MASK\fP | \fBLC_TIME_MASK\fP)"
.br
.RI "Set or query all locale categories at once\&. "
.ti -1c
.RI "#define \fBLC_COLLATE_MASK\fP   (1 << 0)"
.br
.RI "String collation (sorting, comparison) "
.ti -1c
.RI "#define \fBLC_CTYPE_MASK\fP   (1 << 1)"
.br
.RI "Character classification and case mapping\&. "
.ti -1c
.RI "#define \fBLC_MESSAGES_MASK\fP   (1 << 2)"
.br
.RI "Language of diagnostic messages\&. "
.ti -1c
.RI "#define \fBLC_MONETARY_MASK\fP   (1 << 3)"
.br
.RI "Monetary formatting rules\&. "
.ti -1c
.RI "#define \fBLC_NUMERIC_MASK\fP   (1 << 4)"
.br
.RI "Numeric formatting (decimal point, grouping) "
.ti -1c
.RI "#define \fBLC_TIME_MASK\fP   (1 << 5)"
.br
.RI "Date and time formatting\&. "
.ti -1c
.RI "#define \fBLC_GLOBAL_LOCALE\fP   ((\fBlocale_t\fP)0)"
.br
.RI "Identifier of the global local\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fB_platform_locale\fP \fBlocale_t\fP"
.br
.RI "Alais for the __local struct\&. "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBSignPosition\fP { \fBIMPLIED_WITH_PARENTHESES\fP, \fBBEFORE_VALUE_AND_SYMBOL\fP, \fBAFTER_VALUE_AND_SYMBOL\fP, \fBBEFORE_VALUE\fP, \fBAFTER_VALUE\fP }"
.br
.RI "Defines where a sign string should be placed\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlocale_t\fP \fBduplocale\fP (\fBlocale_t\fP)"
.br
.ti -1c
.RI "void \fBfreelocale\fP (\fBlocale_t\fP)"
.br
.ti -1c
.RI "struct \fBlconv\fP * \fBlocaleconv\fP (void)"
.br
.ti -1c
.RI "\fBlocale_t\fP \fBnewlocale\fP (int, const char *, \fBlocale_t\fP)"
.br
.ti -1c
.RI "char * \fBsetlocale\fP (int, const char *)"
.br
.ti -1c
.RI "\fBlocale_t\fP \fBuselocale\fP (\fBlocale_t\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Defines langauge and region specific behaviour\&. 


.PP
\fBSee also\fP
.RS 4
https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/locale.h.html
.RE
.PP
\fBDate\fP
.RS 4
15 December 2025 
.RE
.PP
\fBAuthor\fP
.RS 4
Max Tyson 
.RE
.PP

.PP
Definition in file \fBlocale\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define LC_ALL   0"

.PP
Set or query all locale categories at once\&. 
.PP
Definition at line \fB75\fP of file \fBlocale\&.h\fP\&.
.SS "#define LC_ALL_MASK   (\fBLC_COLLATE_MASK\fP | \fBLC_CTYPE_MASK\fP | \fBLC_MESSAGES_MASK\fP | \fBLC_MONETARY_MASK\fP | \fBLC_NUMERIC_MASK\fP | \fBLC_TIME_MASK\fP)"

.PP
Set or query all locale categories at once\&. 
.PP
Definition at line \fB83\fP of file \fBlocale\&.h\fP\&.
.SS "#define LC_COLLATE   1"

.PP
String collation rules (sorting and comparison order) 
.PP
Definition at line \fB76\fP of file \fBlocale\&.h\fP\&.
.SS "#define LC_COLLATE_MASK   (1 << 0)"

.PP
String collation (sorting, comparison) 
.PP
Definition at line \fB84\fP of file \fBlocale\&.h\fP\&.
.SS "#define LC_CTYPE   2"

.PP
Character classification, case conversion, encoding\&. 
.PP
Definition at line \fB77\fP of file \fBlocale\&.h\fP\&.
.SS "#define LC_CTYPE_MASK   (1 << 1)"

.PP
Character classification and case mapping\&. 
.PP
Definition at line \fB85\fP of file \fBlocale\&.h\fP\&.
.SS "#define LC_GLOBAL_LOCALE   ((\fBlocale_t\fP)0)"

.PP
Identifier of the global local\&. 
.PP
Definition at line \fB91\fP of file \fBlocale\&.h\fP\&.
.SS "#define LC_MESSAGES   3"

.PP
Language used for diagnostic and system messages\&. 
.PP
Definition at line \fB78\fP of file \fBlocale\&.h\fP\&.
.SS "#define LC_MESSAGES_MASK   (1 << 2)"

.PP
Language of diagnostic messages\&. 
.PP
Definition at line \fB86\fP of file \fBlocale\&.h\fP\&.
.SS "#define LC_MONETARY   4"

.PP
Currency symbols, monetary formatting, sign placement\&. 
.PP
Definition at line \fB79\fP of file \fBlocale\&.h\fP\&.
.SS "#define LC_MONETARY_MASK   (1 << 3)"

.PP
Monetary formatting rules\&. 
.PP
Definition at line \fB87\fP of file \fBlocale\&.h\fP\&.
.SS "#define LC_NUMERIC   5"

.PP
Non-monetary numeric formatting (decimal point, grouping) 
.PP
Definition at line \fB80\fP of file \fBlocale\&.h\fP\&.
.SS "#define LC_NUMERIC_MASK   (1 << 4)"

.PP
Numeric formatting (decimal point, grouping) 
.PP
Definition at line \fB88\fP of file \fBlocale\&.h\fP\&.
.SS "#define LC_TIME   6"

.PP
Date and time formatting (month/day names, formats) 
.PP
Definition at line \fB81\fP of file \fBlocale\&.h\fP\&.
.SS "#define LC_TIME_MASK   (1 << 5)"

.PP
Date and time formatting\&. 
.PP
Definition at line \fB89\fP of file \fBlocale\&.h\fP\&.
.SH "Typedef Documentation"
.PP 
.SS "\fBlocale_t\fP"

.PP
Alais for the __local struct\&. 
.PP
Definition at line \fB100\fP of file \fBlocale\&.h\fP\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBSignPosition\fP"

.PP
Defines where a sign string should be placed\&. 
.PP
Definition at line \fB24\fP of file \fBlocale\&.h\fP\&..PP
.nf
24                   {
25 
26     IMPLIED_WITH_PARENTHESES,
27     BEFORE_VALUE_AND_SYMBOL,
28     AFTER_VALUE_AND_SYMBOL,
29     BEFORE_VALUE,
30     AFTER_VALUE,
31 
32 };
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for LibC from the source code\&.
