.TH "sigaction" 3 "Version 0.3" "LibC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sigaction \- Define what happens when receiving a specific signal\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <signal\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "sighandler_t \fBsa_handler\fP"
.br
.RI "Pointer to a signal-catching function or one of the SIG_IGN or SIG_DFL\&. "
.ti -1c
.RI "sigset_t \fBsa_mask\fP"
.br
.RI "Set of signals to be blocked during execution of the signal handling function\&. "
.ti -1c
.RI "int \fBsa_flags\fP"
.br
.RI "Special flags\&. "
.ti -1c
.RI "sigaction_handler_t \fBsa_sigaction\fP"
.br
.RI "Pointer to a signal-catching function\&. (legacy/fast) "
.in -1c
.SH "Detailed Description"
.PP 
Define what happens when receiving a specific signal\&. 


.PP
\fBWarning\fP
.RS 4
Use either sa_handler or sa_sigaction NOT both 
.RE
.PP

.PP
Definition at line \fB129\fP of file \fBsignal\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int sigaction::sa_flags"

.PP
Special flags\&. 
.PP
Definition at line \fB133\fP of file \fBsignal\&.h\fP\&.
.SS "sighandler_t sigaction::sa_handler"

.PP
Pointer to a signal-catching function or one of the SIG_IGN or SIG_DFL\&. 
.PP
Definition at line \fB131\fP of file \fBsignal\&.h\fP\&.
.SS "sigset_t sigaction::sa_mask"

.PP
Set of signals to be blocked during execution of the signal handling function\&. 
.PP
Definition at line \fB132\fP of file \fBsignal\&.h\fP\&.
.SS "sigaction_handler_t sigaction::sa_sigaction"

.PP
Pointer to a signal-catching function\&. (legacy/fast) 
.PP
Definition at line \fB134\fP of file \fBsignal\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LibC from the source code\&.
