.TH "sigevent" 3 "Version 0.3" "LibC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sigevent \- Define how to notify the process when an event is fired\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <signal\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBsigev_notify\fP"
.br
.RI "How to notify upon signaling\&. "
.ti -1c
.RI "int \fBsigev_signo\fP"
.br
.RI "The signal this event is linked to\&. "
.ti -1c
.RI "union \fBsigval\fP \fBsigev_value\fP"
.br
.RI "The signal payload\&. "
.ti -1c
.RI "sigev_notify_function_t \fBsigev_notify_function\fP"
.br
.RI "Function to handle the signal\&. "
.ti -1c
.RI "\fBpthread_attr_t\fP * \fBsigev_notify_attributes\fP"
.br
.RI "Defines the thread to be created to handle the signal\&. "
.in -1c
.SH "Detailed Description"
.PP 
Define how to notify the process when an event is fired\&. 
.PP
Definition at line \fB51\fP of file \fBsignal\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int sigevent::sigev_notify"

.PP
How to notify upon signaling\&. 
.PP
Definition at line \fB53\fP of file \fBsignal\&.h\fP\&.
.SS "\fBpthread_attr_t\fP* sigevent::sigev_notify_attributes"

.PP
Defines the thread to be created to handle the signal\&. 
.PP
Definition at line \fB57\fP of file \fBsignal\&.h\fP\&.
.SS "sigev_notify_function_t sigevent::sigev_notify_function"

.PP
Function to handle the signal\&. 
.PP
Definition at line \fB56\fP of file \fBsignal\&.h\fP\&.
.SS "int sigevent::sigev_signo"

.PP
The signal this event is linked to\&. 
.PP
Definition at line \fB54\fP of file \fBsignal\&.h\fP\&.
.SS "union \fBsigval\fP sigevent::sigev_value"

.PP
The signal payload\&. 
.PP
Definition at line \fB55\fP of file \fBsignal\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LibC from the source code\&.
