.TH "sigval" 3 "Version 0.3" "LibC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sigval \- A payload to pass along with a signal\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <signal\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBsival_int\fP"
.br
.ti -1c
.RI "void * \fBsival_ptr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A payload to pass along with a signal\&. 
.PP
Definition at line \fB40\fP of file \fBsignal\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int sigval::sival_int"

.PP
Definition at line \fB42\fP of file \fBsignal\&.h\fP\&.
.SS "void* sigval::sival_ptr"

.PP
Definition at line \fB43\fP of file \fBsignal\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LibC from the source code\&.
