.TH "stat" 3 "Version 0.3" "LibC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stat \- The status of file\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stat\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBdev_t\fP \fBst_dev\fP"
.br
.RI "Device ID of device containing file\&. "
.ti -1c
.RI "\fBino_t\fP \fBst_ino\fP"
.br
.RI "File serial number\&. "
.ti -1c
.RI "\fBmode_t\fP \fBst_mode\fP"
.br
.RI "Mode of file\&. "
.ti -1c
.RI "\fBnlink_t\fP \fBst_nlink\fP"
.br
.RI "Number of hard links to the file\&. "
.ti -1c
.RI "\fBoff_t\fP \fBst_size\fP"
.br
.RI "In bytes, the file size / symbolic link path size / memory length\&. "
.ti -1c
.RI "\fBuid_t\fP \fBst_uid\fP"
.br
.RI "User ID of file\&. "
.ti -1c
.RI "\fBgid_t\fP \fBst_gid\fP"
.br
.RI "Group ID of file\&. "
.ti -1c
.RI "\fBdev_t\fP \fBst_rdev\fP"
.br
.RI "Device ID (if file is character or block special)\&. "
.ti -1c
.RI "struct \fBtimespec\fP \fBst_atim\fP"
.br
.RI "Last data access timestamp\&. "
.ti -1c
.RI "struct \fBtimespec\fP \fBst_mtim\fP"
.br
.RI "Last data modification timestamp\&. "
.ti -1c
.RI "struct \fBtimespec\fP \fBst_ctim\fP"
.br
.RI "Last file status change timestamp\&. "
.ti -1c
.RI "\fBblksize_t\fP \fBst_blksize\fP"
.br
.RI "The preferred block size\&. "
.ti -1c
.RI "\fBblkcnt_t\fP \fBst_blocks\fP"
.br
.RI "Number of blocks allocated for this object\&. "
.in -1c
.SH "Detailed Description"
.PP 
The status of file\&. 
.PP
Definition at line \fB26\fP of file \fBstat\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "struct \fBtimespec\fP stat::st_atim"

.PP
Last data access timestamp\&. 
.PP
Definition at line \fB39\fP of file \fBstat\&.h\fP\&.
.SS "\fBblksize_t\fP stat::st_blksize"

.PP
The preferred block size\&. 
.PP
Definition at line \fB43\fP of file \fBstat\&.h\fP\&.
.SS "\fBblkcnt_t\fP stat::st_blocks"

.PP
Number of blocks allocated for this object\&. 
.PP
Definition at line \fB44\fP of file \fBstat\&.h\fP\&.
.SS "struct \fBtimespec\fP stat::st_ctim"

.PP
Last file status change timestamp\&. 
.PP
Definition at line \fB41\fP of file \fBstat\&.h\fP\&.
.SS "\fBdev_t\fP stat::st_dev"

.PP
Device ID of device containing file\&. 
.PP
Definition at line \fB28\fP of file \fBstat\&.h\fP\&.
.SS "\fBgid_t\fP stat::st_gid"

.PP
Group ID of file\&. 
.PP
Definition at line \fB36\fP of file \fBstat\&.h\fP\&.
.SS "\fBino_t\fP stat::st_ino"

.PP
File serial number\&. 
.PP
Definition at line \fB29\fP of file \fBstat\&.h\fP\&.
.SS "\fBmode_t\fP stat::st_mode"

.PP
Mode of file\&. 
.PP
Definition at line \fB31\fP of file \fBstat\&.h\fP\&.
.PP
Referenced by \fB_platform_fstat()\fP, and \fB_platform_stat()\fP\&.
.SS "struct \fBtimespec\fP stat::st_mtim"

.PP
Last data modification timestamp\&. 
.PP
Definition at line \fB40\fP of file \fBstat\&.h\fP\&.
.SS "\fBnlink_t\fP stat::st_nlink"

.PP
Number of hard links to the file\&. 
.PP
Definition at line \fB32\fP of file \fBstat\&.h\fP\&.
.SS "\fBdev_t\fP stat::st_rdev"

.PP
Device ID (if file is character or block special)\&. 
.PP
Definition at line \fB37\fP of file \fBstat\&.h\fP\&.
.SS "\fBoff_t\fP stat::st_size"

.PP
In bytes, the file size / symbolic link path size / memory length\&. 
.PP
Definition at line \fB33\fP of file \fBstat\&.h\fP\&.
.SS "\fBuid_t\fP stat::st_uid"

.PP
User ID of file\&. 
.PP
Definition at line \fB35\fP of file \fBstat\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LibC from the source code\&.
