.TH "/home/runner/work/LibC/LibC/include/stddef.h" 3 "Version 0.3" "LibC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/LibC/LibC/include/stddef.h \- Defines fundamental types and macros required by the C language\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <libc_common\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBNULL\fP   ((void*)0)"
.br
.RI "Null pointer constant\&. "
.ti -1c
.RI "#define \fBoffsetof\fP(type,  member)   ((size_t)( (char *)&(((type *)0)\->member) \- (char *)0 ))"
.br
.RI "Offest in bytes of a member from the start of the struct\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef __PTRDIFF_TYPE__ \fBptrdiff_t\fP"
.br
.ti -1c
.RI "typedef __WCHAR_TYPE__ \fBwchar_t\fP"
.br
.ti -1c
.RI "typedef __SIZE_TYPE__ \fBsize_t\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Defines fundamental types and macros required by the C language\&. 


.PP
\fBSee also\fP
.RS 4
https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/stddef.h.html
.RE
.PP
\fBDate\fP
.RS 4
16 December 2025 
.RE
.PP
\fBAuthor\fP
.RS 4
Max Tyson 
.RE
.PP

.PP
Definition in file \fBstddef\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define NULL   ((void*)0)"

.PP
Null pointer constant\&. 
.PP
Definition at line \fB21\fP of file \fBstddef\&.h\fP\&.
.SS "#define offsetof(type, member)   ((size_t)( (char *)&(((type *)0)\->member) \- (char *)0 ))"

.PP
Offest in bytes of a member from the start of the struct\&. 
.PP
Definition at line \fB24\fP of file \fBstddef\&.h\fP\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef __PTRDIFF_TYPE__ ptrdiff_t"

.PP
Definition at line \fB26\fP of file \fBstddef\&.h\fP\&.
.SS "typedef __SIZE_TYPE__ size_t"

.PP
Definition at line \fB28\fP of file \fBstddef\&.h\fP\&.
.SS "typedef __WCHAR_TYPE__ wchar_t"

.PP
Definition at line \fB27\fP of file \fBstddef\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LibC from the source code\&.
