.TH "/home/runner/work/LibC/LibC/include/stdint.h" 3 "Version 0.3" "LibC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/LibC/LibC/include/stdint.h \- Defines sets of integer types having specified widths\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <libc_common\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBINT8_MAX\fP   __INT8_MAX__"
.br
.ti -1c
.RI "#define \fBINT8_MIN\fP   (\-INT8_MAX \- 1)"
.br
.ti -1c
.RI "#define \fBINT_LEAST8_MAX\fP   INT8_MAX"
.br
.ti -1c
.RI "#define \fBINT_LEAST8_MIN\fP   INT8_MIN"
.br
.ti -1c
.RI "#define \fBINT_FAST8_MAX\fP   __INT_FAST8_MAX__"
.br
.ti -1c
.RI "#define \fBINT_FAST8_MIN\fP   (\-INT_FAST8_MAX \- 1)"
.br
.ti -1c
.RI "#define \fBINT8_C\fP(c)   __INT8_C(c)"
.br
.ti -1c
.RI "#define \fBUINT8_MAX\fP   __UINT8_MAX__"
.br
.ti -1c
.RI "#define \fBUINT_LEAST8_MAX\fP   UINT8_MAX"
.br
.ti -1c
.RI "#define \fBUINT_FAST8_MAX\fP   __UINT_FAST8_MAX__"
.br
.ti -1c
.RI "#define \fBUINT8_C\fP(c)   __UINT8_C(c)"
.br
.ti -1c
.RI "#define \fBINT16_MAX\fP   __INT16_MAX__"
.br
.ti -1c
.RI "#define \fBINT16_MIN\fP   (\-INT16_MAX \- 1)"
.br
.ti -1c
.RI "#define \fBINT_LEAST16_MAX\fP   INT16_MAX"
.br
.ti -1c
.RI "#define \fBINT_LEAST16_MIN\fP   INT16_MIN"
.br
.ti -1c
.RI "#define \fBINT_FAST16_MAX\fP   __INT_FAST16_MAX__"
.br
.ti -1c
.RI "#define \fBINT_FAST16_MIN\fP   (\-INT_FAST16_MAX \- 1)"
.br
.ti -1c
.RI "#define \fBINT16_C\fP(c)   __INT16_C(c)"
.br
.ti -1c
.RI "#define \fBUINT16_MAX\fP   __UINT16_MAX__"
.br
.ti -1c
.RI "#define \fBUINT_LEAST16_MAX\fP   UINT16_MAX"
.br
.ti -1c
.RI "#define \fBUINT_FAST16_MAX\fP   __UINT_FAST16_MAX__"
.br
.ti -1c
.RI "#define \fBUINT16_C\fP(c)   __UINT16_C(c)"
.br
.ti -1c
.RI "#define \fBINT32_MAX\fP   __INT32_MAX__"
.br
.ti -1c
.RI "#define \fBINT32_MIN\fP   (\-INT32_MAX \- 1)"
.br
.ti -1c
.RI "#define \fBINT_LEAST32_MAX\fP   INT32_MAX"
.br
.ti -1c
.RI "#define \fBINT_LEAST32_MIN\fP   INT32_MIN"
.br
.ti -1c
.RI "#define \fBINT_FAST32_MAX\fP   __INT_FAST32_MAX__"
.br
.ti -1c
.RI "#define \fBINT_FAST32_MIN\fP   (\-INT_FAST32_MAX \- 1)"
.br
.ti -1c
.RI "#define \fBINT32_C\fP(c)   __INT32_C(c)"
.br
.ti -1c
.RI "#define \fBUINT32_MAX\fP   __UINT32_MAX__"
.br
.ti -1c
.RI "#define \fBUINT_LEAST32_MAX\fP   UINT32_MAX"
.br
.ti -1c
.RI "#define \fBUINT_FAST32_MAX\fP   __UINT_FAST32_MAX__"
.br
.ti -1c
.RI "#define \fBUINT32_C\fP(c)   __UINT32_C(c)"
.br
.ti -1c
.RI "#define \fBINT64_MAX\fP   __INT64_MAX__"
.br
.ti -1c
.RI "#define \fBINT64_MIN\fP   (\-INT64_MAX \- 1)"
.br
.ti -1c
.RI "#define \fBINT_LEAST64_MAX\fP   INT64_MAX"
.br
.ti -1c
.RI "#define \fBINT_LEAST64_MIN\fP   INT64_MIN"
.br
.ti -1c
.RI "#define \fBINT_FAST64_MAX\fP   __INT_FAST64_MAX__"
.br
.ti -1c
.RI "#define \fBINT_FAST64_MIN\fP   (\-INT_FAST64_MAX \- 1)"
.br
.ti -1c
.RI "#define \fBINT64_C\fP(c)   __INT64_C(c)"
.br
.ti -1c
.RI "#define \fBUINT64_MAX\fP   __UINT64_MAX__"
.br
.ti -1c
.RI "#define \fBUINT_LEAST64_MAX\fP   UINT64_MAX"
.br
.ti -1c
.RI "#define \fBUINT_FAST64_MAX\fP   __UINT_FAST64_MAX__"
.br
.ti -1c
.RI "#define \fBUINT64_C\fP(c)   __UINT64_C(c)"
.br
.ti -1c
.RI "#define \fBINTPTR_MAX\fP   __INTPTR_MAX__"
.br
.ti -1c
.RI "#define \fBINTPTR_MIN\fP   (\-INTPTR_MAX \- 1)"
.br
.ti -1c
.RI "#define \fBUINTPTR_MAX\fP   __UINTPTR_MAX__"
.br
.ti -1c
.RI "#define \fBINTMAX_MAX\fP   __INTMAX_MAX__"
.br
.ti -1c
.RI "#define \fBINTMAX_MIN\fP   (\-INTMAX_MAX \- 1)"
.br
.ti -1c
.RI "#define \fBINTMAX_C\fP(c)   __INTMAX_C(c)"
.br
.ti -1c
.RI "#define \fBUINTMAX_MAX\fP   __UINTMAX_MAX__"
.br
.ti -1c
.RI "#define \fBUINTMAX_C\fP(c)   __UINTMAX_C(c)"
.br
.ti -1c
.RI "#define \fBSIZE_MAX\fP   __SIZE_MAX__"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef int8_t \fBint_least8_t\fP"
.br
.ti -1c
.RI "typedef __INT_FAST8_TYPE__ \fBint_fast8_t\fP"
.br
.ti -1c
.RI "typedef __UINT8_TYPE__ \fBuint8_t\fP"
.br
.ti -1c
.RI "typedef uint8_t \fBuint_least8_t\fP"
.br
.ti -1c
.RI "typedef __UINT_FAST8_TYPE__ \fBuint_fast8_t\fP"
.br
.ti -1c
.RI "typedef __INT16_TYPE__ \fBint16_t\fP"
.br
.ti -1c
.RI "typedef int16_t \fBint_least16_t\fP"
.br
.ti -1c
.RI "typedef __INT_FAST16_TYPE__ \fBint_fast16_t\fP"
.br
.ti -1c
.RI "typedef __UINT16_TYPE__ \fBuint16_t\fP"
.br
.ti -1c
.RI "typedef uint16_t \fBuint_least16_t\fP"
.br
.ti -1c
.RI "typedef __UINT_FAST16_TYPE__ \fBuint_fast16_t\fP"
.br
.ti -1c
.RI "typedef __INT32_TYPE__ \fBint32_t\fP"
.br
.ti -1c
.RI "typedef int32_t \fBint_least32_t\fP"
.br
.ti -1c
.RI "typedef __INT_FAST32_TYPE__ \fBint_fast32_t\fP"
.br
.ti -1c
.RI "typedef __UINT32_TYPE__ \fBuint32_t\fP"
.br
.ti -1c
.RI "typedef uint32_t \fBuint_least32_t\fP"
.br
.ti -1c
.RI "typedef __UINT_FAST32_TYPE__ \fBuint_fast32_t\fP"
.br
.ti -1c
.RI "typedef __INT64_TYPE__ \fBint64_t\fP"
.br
.ti -1c
.RI "typedef int64_t \fBint_least64_t\fP"
.br
.ti -1c
.RI "typedef __INT_FAST64_TYPE__ \fBint_fast64_t\fP"
.br
.ti -1c
.RI "typedef __UINT64_TYPE__ \fBuint64_t\fP"
.br
.ti -1c
.RI "typedef uint64_t \fBuint_least64_t\fP"
.br
.ti -1c
.RI "typedef __UINT_FAST64_TYPE__ \fBuint_fast64_t\fP"
.br
.ti -1c
.RI "typedef __INTPTR_TYPE__ \fBintptr_t\fP"
.br
.ti -1c
.RI "typedef __UINTPTR_TYPE__ \fBuintptr_t\fP"
.br
.ti -1c
.RI "typedef __INTMAX_TYPE__ \fBintmax_t\fP"
.br
.ti -1c
.RI "typedef __UINTMAX_TYPE__ \fBuintmax_t\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "CPP_START typedef __INT8_TYPE__ \fBint8_t\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Defines sets of integer types having specified widths\&. 


.PP
\fBSee also\fP
.RS 4
https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/stdint.h.html
.RE
.PP
\fBDate\fP
.RS 4
15 December 2025 
.RE
.PP
\fBAuthor\fP
.RS 4
Max Tyson 
.RE
.PP

.PP
Definition in file \fBstdint\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define INT16_C(c)   __INT16_C(c)"

.PP
Definition at line \fB49\fP of file \fBstdint\&.h\fP\&.
.SS "#define INT16_MAX   __INT16_MAX__"

.PP
Definition at line \fB43\fP of file \fBstdint\&.h\fP\&.
.SS "#define INT16_MIN   (\-INT16_MAX \- 1)"

.PP
Definition at line \fB44\fP of file \fBstdint\&.h\fP\&.
.SS "#define INT32_C(c)   __INT32_C(c)"

.PP
Definition at line \fB70\fP of file \fBstdint\&.h\fP\&.
.SS "#define INT32_MAX   __INT32_MAX__"

.PP
Definition at line \fB64\fP of file \fBstdint\&.h\fP\&.
.SS "#define INT32_MIN   (\-INT32_MAX \- 1)"

.PP
Definition at line \fB65\fP of file \fBstdint\&.h\fP\&.
.SS "#define INT64_C(c)   __INT64_C(c)"

.PP
Definition at line \fB91\fP of file \fBstdint\&.h\fP\&.
.SS "#define INT64_MAX   __INT64_MAX__"

.PP
Definition at line \fB85\fP of file \fBstdint\&.h\fP\&.
.SS "#define INT64_MIN   (\-INT64_MAX \- 1)"

.PP
Definition at line \fB86\fP of file \fBstdint\&.h\fP\&.
.SS "#define INT8_C(c)   __INT8_C(c)"

.PP
Definition at line \fB28\fP of file \fBstdint\&.h\fP\&.
.SS "#define INT8_MAX   __INT8_MAX__"

.PP
Definition at line \fB22\fP of file \fBstdint\&.h\fP\&.
.SS "#define INT8_MIN   (\-INT8_MAX \- 1)"

.PP
Definition at line \fB23\fP of file \fBstdint\&.h\fP\&.
.SS "#define INT_FAST16_MAX   __INT_FAST16_MAX__"

.PP
Definition at line \fB47\fP of file \fBstdint\&.h\fP\&.
.SS "#define INT_FAST16_MIN   (\-INT_FAST16_MAX \- 1)"

.PP
Definition at line \fB48\fP of file \fBstdint\&.h\fP\&.
.SS "#define INT_FAST32_MAX   __INT_FAST32_MAX__"

.PP
Definition at line \fB68\fP of file \fBstdint\&.h\fP\&.
.SS "#define INT_FAST32_MIN   (\-INT_FAST32_MAX \- 1)"

.PP
Definition at line \fB69\fP of file \fBstdint\&.h\fP\&.
.SS "#define INT_FAST64_MAX   __INT_FAST64_MAX__"

.PP
Definition at line \fB89\fP of file \fBstdint\&.h\fP\&.
.SS "#define INT_FAST64_MIN   (\-INT_FAST64_MAX \- 1)"

.PP
Definition at line \fB90\fP of file \fBstdint\&.h\fP\&.
.SS "#define INT_FAST8_MAX   __INT_FAST8_MAX__"

.PP
Definition at line \fB26\fP of file \fBstdint\&.h\fP\&.
.SS "#define INT_FAST8_MIN   (\-INT_FAST8_MAX \- 1)"

.PP
Definition at line \fB27\fP of file \fBstdint\&.h\fP\&.
.SS "#define INT_LEAST16_MAX   INT16_MAX"

.PP
Definition at line \fB45\fP of file \fBstdint\&.h\fP\&.
.SS "#define INT_LEAST16_MIN   INT16_MIN"

.PP
Definition at line \fB46\fP of file \fBstdint\&.h\fP\&.
.SS "#define INT_LEAST32_MAX   INT32_MAX"

.PP
Definition at line \fB66\fP of file \fBstdint\&.h\fP\&.
.SS "#define INT_LEAST32_MIN   INT32_MIN"

.PP
Definition at line \fB67\fP of file \fBstdint\&.h\fP\&.
.SS "#define INT_LEAST64_MAX   INT64_MAX"

.PP
Definition at line \fB87\fP of file \fBstdint\&.h\fP\&.
.SS "#define INT_LEAST64_MIN   INT64_MIN"

.PP
Definition at line \fB88\fP of file \fBstdint\&.h\fP\&.
.SS "#define INT_LEAST8_MAX   INT8_MAX"

.PP
Definition at line \fB24\fP of file \fBstdint\&.h\fP\&.
.SS "#define INT_LEAST8_MIN   INT8_MIN"

.PP
Definition at line \fB25\fP of file \fBstdint\&.h\fP\&.
.SS "#define INTMAX_C(c)   __INTMAX_C(c)"

.PP
Definition at line \fB115\fP of file \fBstdint\&.h\fP\&.
.SS "#define INTMAX_MAX   __INTMAX_MAX__"

.PP
Definition at line \fB113\fP of file \fBstdint\&.h\fP\&.
.SS "#define INTMAX_MIN   (\-INTMAX_MAX \- 1)"

.PP
Definition at line \fB114\fP of file \fBstdint\&.h\fP\&.
.SS "#define INTPTR_MAX   __INTPTR_MAX__"

.PP
Definition at line \fB104\fP of file \fBstdint\&.h\fP\&.
.SS "#define INTPTR_MIN   (\-INTPTR_MAX \- 1)"

.PP
Definition at line \fB105\fP of file \fBstdint\&.h\fP\&.
.SS "#define SIZE_MAX   __SIZE_MAX__"

.PP
Definition at line \fB124\fP of file \fBstdint\&.h\fP\&.
.SS "#define UINT16_C(c)   __UINT16_C(c)"

.PP
Definition at line \fB58\fP of file \fBstdint\&.h\fP\&.
.SS "#define UINT16_MAX   __UINT16_MAX__"

.PP
Definition at line \fB55\fP of file \fBstdint\&.h\fP\&.
.SS "#define UINT32_C(c)   __UINT32_C(c)"

.PP
Definition at line \fB79\fP of file \fBstdint\&.h\fP\&.
.SS "#define UINT32_MAX   __UINT32_MAX__"

.PP
Definition at line \fB76\fP of file \fBstdint\&.h\fP\&.
.SS "#define UINT64_C(c)   __UINT64_C(c)"

.PP
Definition at line \fB100\fP of file \fBstdint\&.h\fP\&.
.SS "#define UINT64_MAX   __UINT64_MAX__"

.PP
Definition at line \fB97\fP of file \fBstdint\&.h\fP\&.
.SS "#define UINT8_C(c)   __UINT8_C(c)"

.PP
Definition at line \fB37\fP of file \fBstdint\&.h\fP\&.
.SS "#define UINT8_MAX   __UINT8_MAX__"

.PP
Definition at line \fB34\fP of file \fBstdint\&.h\fP\&.
.SS "#define UINT_FAST16_MAX   __UINT_FAST16_MAX__"

.PP
Definition at line \fB57\fP of file \fBstdint\&.h\fP\&.
.SS "#define UINT_FAST32_MAX   __UINT_FAST32_MAX__"

.PP
Definition at line \fB78\fP of file \fBstdint\&.h\fP\&.
.SS "#define UINT_FAST64_MAX   __UINT_FAST64_MAX__"

.PP
Definition at line \fB99\fP of file \fBstdint\&.h\fP\&.
.SS "#define UINT_FAST8_MAX   __UINT_FAST8_MAX__"

.PP
Definition at line \fB36\fP of file \fBstdint\&.h\fP\&.
.SS "#define UINT_LEAST16_MAX   UINT16_MAX"

.PP
Definition at line \fB56\fP of file \fBstdint\&.h\fP\&.
.SS "#define UINT_LEAST32_MAX   UINT32_MAX"

.PP
Definition at line \fB77\fP of file \fBstdint\&.h\fP\&.
.SS "#define UINT_LEAST64_MAX   UINT64_MAX"

.PP
Definition at line \fB98\fP of file \fBstdint\&.h\fP\&.
.SS "#define UINT_LEAST8_MAX   UINT8_MAX"

.PP
Definition at line \fB35\fP of file \fBstdint\&.h\fP\&.
.SS "#define UINTMAX_C(c)   __UINTMAX_C(c)"

.PP
Definition at line \fB120\fP of file \fBstdint\&.h\fP\&.
.SS "#define UINTMAX_MAX   __UINTMAX_MAX__"

.PP
Definition at line \fB119\fP of file \fBstdint\&.h\fP\&.
.SS "#define UINTPTR_MAX   __UINTPTR_MAX__"

.PP
Definition at line \fB109\fP of file \fBstdint\&.h\fP\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef __INT16_TYPE__ int16_t"

.PP
Definition at line \fB40\fP of file \fBstdint\&.h\fP\&.
.SS "typedef __INT32_TYPE__ int32_t"

.PP
Definition at line \fB61\fP of file \fBstdint\&.h\fP\&.
.SS "typedef __INT64_TYPE__ int64_t"

.PP
Definition at line \fB82\fP of file \fBstdint\&.h\fP\&.
.SS "typedef __INT_FAST16_TYPE__ int_fast16_t"

.PP
Definition at line \fB42\fP of file \fBstdint\&.h\fP\&.
.SS "typedef __INT_FAST32_TYPE__ int_fast32_t"

.PP
Definition at line \fB63\fP of file \fBstdint\&.h\fP\&.
.SS "typedef __INT_FAST64_TYPE__ int_fast64_t"

.PP
Definition at line \fB84\fP of file \fBstdint\&.h\fP\&.
.SS "typedef __INT_FAST8_TYPE__ int_fast8_t"

.PP
Definition at line \fB21\fP of file \fBstdint\&.h\fP\&.
.SS "typedef int16_t int_least16_t"

.PP
Definition at line \fB41\fP of file \fBstdint\&.h\fP\&.
.SS "typedef int32_t int_least32_t"

.PP
Definition at line \fB62\fP of file \fBstdint\&.h\fP\&.
.SS "typedef int64_t int_least64_t"

.PP
Definition at line \fB83\fP of file \fBstdint\&.h\fP\&.
.SS "typedef int8_t int_least8_t"

.PP
Definition at line \fB20\fP of file \fBstdint\&.h\fP\&.
.SS "typedef __INTMAX_TYPE__ intmax_t"

.PP
Definition at line \fB112\fP of file \fBstdint\&.h\fP\&.
.SS "typedef __INTPTR_TYPE__ intptr_t"

.PP
Definition at line \fB103\fP of file \fBstdint\&.h\fP\&.
.SS "typedef __UINT16_TYPE__ uint16_t"

.PP
Definition at line \fB52\fP of file \fBstdint\&.h\fP\&.
.SS "typedef __UINT32_TYPE__ uint32_t"

.PP
Definition at line \fB73\fP of file \fBstdint\&.h\fP\&.
.SS "typedef __UINT64_TYPE__ uint64_t"

.PP
Definition at line \fB94\fP of file \fBstdint\&.h\fP\&.
.SS "typedef __UINT8_TYPE__ uint8_t"

.PP
Definition at line \fB31\fP of file \fBstdint\&.h\fP\&.
.SS "typedef __UINT_FAST16_TYPE__ uint_fast16_t"

.PP
Definition at line \fB54\fP of file \fBstdint\&.h\fP\&.
.SS "typedef __UINT_FAST32_TYPE__ uint_fast32_t"

.PP
Definition at line \fB75\fP of file \fBstdint\&.h\fP\&.
.SS "typedef __UINT_FAST64_TYPE__ uint_fast64_t"

.PP
Definition at line \fB96\fP of file \fBstdint\&.h\fP\&.
.SS "typedef __UINT_FAST8_TYPE__ uint_fast8_t"

.PP
Definition at line \fB33\fP of file \fBstdint\&.h\fP\&.
.SS "typedef uint16_t uint_least16_t"

.PP
Definition at line \fB53\fP of file \fBstdint\&.h\fP\&.
.SS "typedef uint32_t uint_least32_t"

.PP
Definition at line \fB74\fP of file \fBstdint\&.h\fP\&.
.SS "typedef uint64_t uint_least64_t"

.PP
Definition at line \fB95\fP of file \fBstdint\&.h\fP\&.
.SS "typedef uint8_t uint_least8_t"

.PP
Definition at line \fB32\fP of file \fBstdint\&.h\fP\&.
.SS "typedef __UINTMAX_TYPE__ uintmax_t"

.PP
Definition at line \fB118\fP of file \fBstdint\&.h\fP\&.
.SS "typedef __UINTPTR_TYPE__ uintptr_t"

.PP
Definition at line \fB108\fP of file \fBstdint\&.h\fP\&.
.SH "Variable Documentation"
.PP 
.SS "CPP_START typedef __INT8_TYPE__ int8_t"

.PP
Definition at line \fB19\fP of file \fBstdint\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LibC from the source code\&.
