.TH "timespec" 3 "Version 0.3" "LibC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
timespec \- Defines a precise moment in time\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <time\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBtime_t\fP \fBtv_sec\fP"
.br
.RI "Whole seconds\&. "
.ti -1c
.RI "long \fBtv_nsec\fP"
.br
.RI "Nanoseconds 0 - 999,999,999\&. "
.in -1c
.SH "Detailed Description"
.PP 
Defines a precise moment in time\&. 
.PP
Definition at line \fB43\fP of file \fBtime\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "long timespec::tv_nsec"

.PP
Nanoseconds 0 - 999,999,999\&. 
.PP
Definition at line \fB46\fP of file \fBtime\&.h\fP\&.
.SS "\fBtime_t\fP timespec::tv_sec"

.PP
Whole seconds\&. 
.PP
Definition at line \fB45\fP of file \fBtime\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LibC from the source code\&.
