.TH "/home/runner/work/LibC/LibC/src/time.c" 3 "Version 0.3" "LibC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/LibC/LibC/src/time.c \- Implements time functions\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <time\&.h>\fP
.br

.SH "Detailed Description"
.PP 
Implements time functions\&. 


.PP
\fBDate\fP
.RS 4
15 December 2025 
.RE
.PP
\fBAuthor\fP
.RS 4
Max Tyson 
.RE
.PP

.PP
Definition in file \fBtime\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LibC from the source code\&.
