.TH "tm" 3 "Version 0.3" "LibC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tm \- Defines a moment in time\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <time\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBtm_sec\fP"
.br
.RI "Seconds 0-60\&. "
.ti -1c
.RI "int \fBtm_min\fP"
.br
.RI "Minutes 0-59\&. "
.ti -1c
.RI "int \fBtm_hour\fP"
.br
.RI "Hour 0-23\&. "
.ti -1c
.RI "int \fBtm_mday\fP"
.br
.RI "Day of month 1-31\&. "
.ti -1c
.RI "int \fBtm_mon\fP"
.br
.RI "Month of year 0-11\&. "
.ti -1c
.RI "int \fBtm_year\fP"
.br
.RI "Years since 1900\&. "
.ti -1c
.RI "int \fBtm_wday\fP"
.br
.RI "Day of week 0-6 (Sunday = 0) "
.ti -1c
.RI "int \fBtm_yday\fP"
.br
.RI "Day of year 0-365\&. "
.ti -1c
.RI "int \fBtm_isdst\fP"
.br
.RI "Daylight Savings flag (positive = true, 0 = false, negative = no info) "
.in -1c
.SH "Detailed Description"
.PP 
Defines a moment in time\&. 
.PP
Definition at line \fB25\fP of file \fBtime\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int tm::tm_hour"

.PP
Hour 0-23\&. 
.PP
Definition at line \fB29\fP of file \fBtime\&.h\fP\&.
.SS "int tm::tm_isdst"

.PP
Daylight Savings flag (positive = true, 0 = false, negative = no info) 
.PP
Definition at line \fB35\fP of file \fBtime\&.h\fP\&.
.SS "int tm::tm_mday"

.PP
Day of month 1-31\&. 
.PP
Definition at line \fB30\fP of file \fBtime\&.h\fP\&.
.SS "int tm::tm_min"

.PP
Minutes 0-59\&. 
.PP
Definition at line \fB28\fP of file \fBtime\&.h\fP\&.
.SS "int tm::tm_mon"

.PP
Month of year 0-11\&. 
.PP
Definition at line \fB31\fP of file \fBtime\&.h\fP\&.
.SS "int tm::tm_sec"

.PP
Seconds 0-60\&. 
.PP
Definition at line \fB27\fP of file \fBtime\&.h\fP\&.
.SS "int tm::tm_wday"

.PP
Day of week 0-6 (Sunday = 0) 
.PP
Definition at line \fB33\fP of file \fBtime\&.h\fP\&.
.SS "int tm::tm_yday"

.PP
Day of year 0-365\&. 
.PP
Definition at line \fB34\fP of file \fBtime\&.h\fP\&.
.SS "int tm::tm_year"

.PP
Years since 1900\&. 
.PP
Definition at line \fB32\fP of file \fBtime\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LibC from the source code\&.
