.TH "todo" 3 "Version 0.3" "LibC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Todo List 
.PP

.IP "\fBMember \fBenviron\fP \fP" 1c
this isnt platform specific  
.IP "\fBFile \fBerrno\&.h\fP \fP" 1c
Linux port / remove specifics  
.IP "\fBFile \fBstat\&.h\fP \fP" 1c
S_IFIFO etc are linux specific, move to platform (same for S_TYPEISMQ)  
.IP "\fBFile \fBwait\&.h\fP \fP" 1c
status layout is linux specific, fix 
.PP

