.TH "/home/runner/work/LibC/LibC/include/sys/types.h" 3 "Version 0.3" "LibC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/LibC/LibC/include/sys/types.h \- Defines the common types used throughout libc\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <libc_common\&.h>\fP
.br
\fC#include <stdint\&.h>\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef int64_t \fBblksize_t\fP"
.br
.RI "Size of a single file\&. "
.ti -1c
.RI "typedef uint64_t \fBfsblkcnt_t\fP"
.br
.RI "Number of block in the whole filesystem\&. "
.ti -1c
.RI "typedef uint64_t \fBfsfilcnt_t\fP"
.br
.RI "Number of inodes in the whole filesystem\&. "
.ti -1c
.RI "typedef uint64_t \fBino_t\fP"
.br
.RI "Inode number\&. "
.ti -1c
.RI "typedef uint64_t \fBnlink_t\fP"
.br
.RI "Hardlink count\&. "
.ti -1c
.RI "typedef uint64_t \fBoff_t\fP"
.br
.RI "How many bytes offset into a file\&. "
.ti -1c
.RI "typedef uint32_t \fBmode_t\fP"
.br
.RI "File type and permissions (bitfield: type | permissions) "
.ti -1c
.RI "typedef int64_t \fBclock_t\fP"
.br
.RI "CPU time in ticks\&. "
.ti -1c
.RI "typedef int32_t \fBclockid_t\fP"
.br
.RI "Clock selector ID\&. "
.ti -1c
.RI "typedef int64_t \fBtime_t\fP"
.br
.RI "Seconds since epoch\&. "
.ti -1c
.RI "typedef int64_t \fBsuseconds_t\fP"
.br
.RI "Microseconds\&. "
.ti -1c
.RI "typedef uintptr_t \fBtimer_t\fP"
.br
.RI "Timer handle\&. "
.ti -1c
.RI "typedef uint64_t \fBdev_t\fP"
.br
.RI "Device ID\&. "
.ti -1c
.RI "typedef int32_t \fBkey_t\fP"
.br
.RI "IPC Lookup key\&. "
.ti -1c
.RI "typedef int32_t \fBpid_t\fP"
.br
.RI "Process ID (negatives for groups) "
.ti -1c
.RI "typedef uint32_t \fBid_t\fP"
.br
.RI "Generic ID\&. "
.ti -1c
.RI "typedef \fBid_t\fP \fBuid_t\fP"
.br
.RI "User ID\&. "
.ti -1c
.RI "typedef \fBid_t\fP \fBgid_t\fP"
.br
.RI "Group ID\&. "
.ti -1c
.RI "typedef uintptr_t \fBpthread_t\fP"
.br
.RI "Thread reference\&. "
.ti -1c
.RI "typedef uint32_t \fBpthread_key_t\fP"
.br
.RI "Thread data key index\&. "
.ti -1c
.RI "typedef int32_t \fBpthread_once_t\fP"
.br
.RI "Thread init state\&. "
.ti -1c
.RI "typedef uintptr_t \fBpthread_attr_t\fP"
.br
.RI "Thread attribute object\&. "
.ti -1c
.RI "typedef uintptr_t \fBpthread_barrier_t\fP"
.br
.ti -1c
.RI "typedef uintptr_t \fBpthread_barrierattr_t\fP"
.br
.ti -1c
.RI "typedef uintptr_t \fBpthread_cond_t\fP"
.br
.ti -1c
.RI "typedef uintptr_t \fBpthread_condattr_t\fP"
.br
.ti -1c
.RI "typedef uintptr_t \fBpthread_mutex_t\fP"
.br
.ti -1c
.RI "typedef uintptr_t \fBpthread_mutexattr_t\fP"
.br
.ti -1c
.RI "typedef uintptr_t \fBpthread_rwlock_t\fP"
.br
.ti -1c
.RI "typedef uintptr_t \fBpthread_rwlockattr_t\fP"
.br
.ti -1c
.RI "typedef uintptr_t \fBpthread_spinlock_t\fP"
.br
.ti -1c
.RI "typedef uint32_t \fBtrace_id_t\fP"
.br
.RI "The ID of a trace stream\&. "
.ti -1c
.RI "typedef uint32_t \fBtrace_event_id_t\fP"
.br
.RI "The ID of a trace event\&. "
.ti -1c
.RI "typedef uintptr_t \fBtrace_attr_t\fP"
.br
.RI "The object containing the trace atributes\&. "
.ti -1c
.RI "typedef uintptr_t \fBtrace_event_set_t\fP"
.br
.RI "The object containing the event type\&. "
.ti -1c
.RI "typedef __SIZE_TYPE__ \fBsize_t\fP"
.br
.RI "Largest size this system can store\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "typedef \fB__typeof__\fP ((size_t) 0 \- 1) ssize_t"
.br
.RI "Largest signed size this system can store\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "CPP_START typedef int64_t \fBblkcnt_t\fP"
.br
.RI "Number of blocks in a file\&. "
.in -1c
.SH "Detailed Description"
.PP 
Defines the common types used throughout libc\&. 


.PP
\fBSee also\fP
.RS 4
https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/sys_stat.h.html
.RE
.PP
\fBDate\fP
.RS 4
15 December 2025 
.RE
.PP
\fBAuthor\fP
.RS 4
Max Tyson 
.RE
.PP

.PP
Definition in file \fBtypes\&.h\fP\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef int64_t \fBblksize_t\fP"

.PP
Size of a single file\&. 
.PP
Definition at line \fB20\fP of file \fBtypes\&.h\fP\&.
.SS "typedef int64_t \fBclock_t\fP"

.PP
CPU time in ticks\&. 
.PP
Definition at line \fB28\fP of file \fBtypes\&.h\fP\&.
.SS "typedef int32_t \fBclockid_t\fP"

.PP
Clock selector ID\&. 
.PP
Definition at line \fB29\fP of file \fBtypes\&.h\fP\&.
.SS "typedef uint64_t \fBdev_t\fP"

.PP
Device ID\&. 
.PP
Definition at line \fB34\fP of file \fBtypes\&.h\fP\&.
.SS "typedef uint64_t \fBfsblkcnt_t\fP"

.PP
Number of block in the whole filesystem\&. 
.PP
Definition at line \fB21\fP of file \fBtypes\&.h\fP\&.
.SS "typedef uint64_t \fBfsfilcnt_t\fP"

.PP
Number of inodes in the whole filesystem\&. 
.PP
Definition at line \fB22\fP of file \fBtypes\&.h\fP\&.
.SS "typedef \fBid_t\fP \fBgid_t\fP"

.PP
Group ID\&. 
.PP
Definition at line \fB40\fP of file \fBtypes\&.h\fP\&.
.SS "typedef uint32_t \fBid_t\fP"

.PP
Generic ID\&. 
.PP
Definition at line \fB38\fP of file \fBtypes\&.h\fP\&.
.SS "typedef uint64_t \fBino_t\fP"

.PP
Inode number\&. 
.PP
Definition at line \fB23\fP of file \fBtypes\&.h\fP\&.
.SS "typedef int32_t \fBkey_t\fP"

.PP
IPC Lookup key\&. 
.PP
Definition at line \fB35\fP of file \fBtypes\&.h\fP\&.
.SS "typedef uint32_t \fBmode_t\fP"

.PP
File type and permissions (bitfield: type | permissions) 
.PP
Definition at line \fB26\fP of file \fBtypes\&.h\fP\&.
.SS "typedef uint64_t \fBnlink_t\fP"

.PP
Hardlink count\&. 
.PP
Definition at line \fB24\fP of file \fBtypes\&.h\fP\&.
.SS "typedef uint64_t \fBoff_t\fP"

.PP
How many bytes offset into a file\&. 
.PP
Definition at line \fB25\fP of file \fBtypes\&.h\fP\&.
.SS "typedef int32_t \fBpid_t\fP"

.PP
Process ID (negatives for groups) 
.PP
Definition at line \fB37\fP of file \fBtypes\&.h\fP\&.
.SS "typedef uintptr_t \fBpthread_attr_t\fP"

.PP
Thread attribute object\&. 
.PP
Definition at line \fB46\fP of file \fBtypes\&.h\fP\&.
.SS "typedef uintptr_t pthread_barrier_t"

.PP
Definition at line \fB47\fP of file \fBtypes\&.h\fP\&.
.SS "typedef uintptr_t pthread_barrierattr_t"

.PP
Definition at line \fB48\fP of file \fBtypes\&.h\fP\&.
.SS "typedef uintptr_t pthread_cond_t"

.PP
Definition at line \fB49\fP of file \fBtypes\&.h\fP\&.
.SS "typedef uintptr_t pthread_condattr_t"

.PP
Definition at line \fB50\fP of file \fBtypes\&.h\fP\&.
.SS "typedef uint32_t \fBpthread_key_t\fP"

.PP
Thread data key index\&. 
.PP
Definition at line \fB43\fP of file \fBtypes\&.h\fP\&.
.SS "typedef uintptr_t pthread_mutex_t"

.PP
Definition at line \fB51\fP of file \fBtypes\&.h\fP\&.
.SS "typedef uintptr_t pthread_mutexattr_t"

.PP
Definition at line \fB52\fP of file \fBtypes\&.h\fP\&.
.SS "typedef int32_t \fBpthread_once_t\fP"

.PP
Thread init state\&. 
.PP
Definition at line \fB44\fP of file \fBtypes\&.h\fP\&.
.SS "typedef uintptr_t pthread_rwlock_t"

.PP
Definition at line \fB53\fP of file \fBtypes\&.h\fP\&.
.SS "typedef uintptr_t pthread_rwlockattr_t"

.PP
Definition at line \fB54\fP of file \fBtypes\&.h\fP\&.
.SS "typedef uintptr_t pthread_spinlock_t"

.PP
Definition at line \fB55\fP of file \fBtypes\&.h\fP\&.
.SS "typedef uintptr_t \fBpthread_t\fP"

.PP
Thread reference\&. 
.PP
Definition at line \fB42\fP of file \fBtypes\&.h\fP\&.
.SS "typedef __SIZE_TYPE__ size_t"

.PP
Largest size this system can store\&. 
.PP
Definition at line \fB62\fP of file \fBtypes\&.h\fP\&.
.SS "typedef int64_t \fBsuseconds_t\fP"

.PP
Microseconds\&. 
.PP
Definition at line \fB31\fP of file \fBtypes\&.h\fP\&.
.SS "typedef int64_t \fBtime_t\fP"

.PP
Seconds since epoch\&. 
.PP
Definition at line \fB30\fP of file \fBtypes\&.h\fP\&.
.SS "typedef uintptr_t \fBtimer_t\fP"

.PP
Timer handle\&. 
.PP
Definition at line \fB32\fP of file \fBtypes\&.h\fP\&.
.SS "typedef uintptr_t \fBtrace_attr_t\fP"

.PP
The object containing the trace atributes\&. 
.PP
Definition at line \fB59\fP of file \fBtypes\&.h\fP\&.
.SS "typedef uint32_t \fBtrace_event_id_t\fP"

.PP
The ID of a trace event\&. 
.PP
Definition at line \fB58\fP of file \fBtypes\&.h\fP\&.
.SS "typedef uintptr_t \fBtrace_event_set_t\fP"

.PP
The object containing the event type\&. 
.PP
Definition at line \fB60\fP of file \fBtypes\&.h\fP\&.
.SS "typedef uint32_t \fBtrace_id_t\fP"

.PP
The ID of a trace stream\&. 
.PP
Definition at line \fB57\fP of file \fBtypes\&.h\fP\&.
.SS "typedef \fBid_t\fP \fBuid_t\fP"

.PP
User ID\&. 
.PP
Definition at line \fB39\fP of file \fBtypes\&.h\fP\&.
.SH "Variable Documentation"
.PP 
.SS "CPP_START typedef int64_t blkcnt_t"

.PP
Number of blocks in a file\&. 
.PP
Definition at line \fB19\fP of file \fBtypes\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LibC from the source code\&.
